### ISSUE TITLE
Error when applying with latest version of spicetify-cli (v2.2.5)

### ISSUE THREAD

**Issue by fosam** [Daksh777/SpotifyNoPremium#1]
Hello @Daksh777 

When i apply this theme using the latest version (v2.2.5) i get tthe following error:

<pre>
spicetify apply
spicetify v2.2.5
<b>error Cannot open file C:\Users\test\Desktop\spicetify-cli\Themes\SpotifyNoPremium\color.ini</b>
Copying raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
success Spotify is spiced up!
</pre>

Then when i opened Spotify i could not see something wrong as a result of this error.

In versions below v2.2.5 this error does not occur.

Can you check if this error has any impact on the theme?

**Comment by Daksh777** [comment]
Thanks for reporting that @fosam 

Seems like Spicetify now has a check for the color.ini file, however we don't need any custom theme at all.
You can either ignore the error or I can create a blank color.ini file so it will give print "Err" in the console.
![image](https://user-images.githubusercontent.com/43648146/120102224-96291880-c167-11eb-9977-b51ef59d85a1.png)

None of these errors will actually cause any problems but let me know if you want me to create a blank color.ini file so you don't see a red error text.

**Comment by fosam** [comment]
Yea, that is what i was thinking, this theme only modifies the "placeholder" and removes the "Upgrade" button so there's no requirement for a `color.ini` as this theme preserves the original stock Spotify theme, and for people like me who like the stock theme, this is great!

The idea to replace the red error message with the one shown in the screenshot is great too, for me at least i would be more comfortable with that than seeing the "scary" red error message :)

**Comment by Daksh777** [comment]
Alright, I created a blank `color.ini`, thanks for contributing!

**Comment by fosam** [comment]
Thank you!

I have just download the theme, but how come i did not get the `Err` like you?

Here is my `apply` command:

```
spicetify v2.2.5
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
success Spotify is spiced up!
```

**Comment by Daksh777** [comment]
Well that is weird 😅
I still do see the "Err" message.

Are you on macOS?

**Comment by fosam** [comment]
Windows 10

**Comment by Daksh777** [comment]
I still do get that error, very weird 👀

**Comment by fosam** [comment]
Hmm, at least the blank `color.ini` fixed the issue for me and i get no errors at all, but that `Err` you get must be something not related to `color.ini`?
Im not sure...

**Comment by Daksh777** [comment]
Well, I don't know either but it works with the blank `color.ini` file.
I'll have a look at Spicetify's source code later and check.
