### ISSUE TITLE
Full Uninstall

### ISSUE THREAD

**Issue by SergioBareaCela** [Daksh777/SpotifyNoPremium#103]
I need to know how can i uninstall completely because for some reason, even if i remove manually the folders of spicetify and reinstall spotify, ads are brocken like this and i cant add friend if they are not from facebook.
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/92882848/bdc7596a-7b53-46e5-940b-5c39c9808ead)

**Comment by Pirassal** [comment]
Same problem here; I already uninstalled spicetify, uninstalled spotify and deleted all spotify and spicetify folders and restarted my computer. I continue with this problem of broken visual advertisements and for some reason my spotify does not have ads (audio) even though I did not put anything on it after uninstalling everything and reinstalling only spotify. I don't have any private dns or anything like that.

If you can find a solution I would be very grateful.

(sorry for my bad english from google translator)

**Comment by Daksh777** [comment]
Any update @SergioBareaCela?
