### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by MONKE121** [Daksh777/SpotifyNoPremium#105]
I try the SpotifyNoPremium a while ago when the new update of Spotify it didn't work work anymore, I don't know any code . I just search PremiumSpotify on Github and I found your prodject and I tried it and it work. but now it stop working for I don't know the reason . hope you can help 
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/112748093/1b6a8db8-feed-470a-8187-842e7d433a0d)

**Comment by Daksh777** [comment]
Hey @MONKE121, apologies for the delay.

Please make sure to click no when the script asks if you have Spicetify installed and then it will work. Let me know if you need any more help!
