### ISSUE TITLE
Remove "update spicetify" button 

### ISSUE THREAD

**Issue by rpgdev** [Daksh777/SpotifyNoPremium#106]
Not sure if the theme is misbehaving or this is a feature request. The theme has removed the upgrade Spotify button but why do we still get the "upgrade spicetify" one? Like, if we don't care for the Spotify one why should we care about upgrading spicetify once we have setup Spotify the way we like it? Once I have setup spotify the way I like it I really don't care if Spicetify is updated or not. Plus it screws up the UI, I think it should be removed.
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/20094474/943a84e1-4931-4b5d-bab0-6fd14337db91)

**Comment by Daksh777** [comment]
Hey @rpgdev, sorry for the late reply!
Unfortunately, it's not possible to remove it, since it's from Spicetify CLI directly. I suggest you raise this issue in the main repo itself: https://github.com/spicetify/spicetify-cli

**Comment by rpgdev** [comment]
Thanks @Daksh777 guess I'll just get used to it. Thanks for your work on the theme!

**Comment by Daksh777** [comment]
I would've said that we can hide it using CSS but it's using global classes so it would hide all top bar buttons :(
I'll raise an issue in the main repo for you, thank you for being patient! :)

**Comment by Daksh777** [comment]
https://github.com/spicetify/spicetify-cli/issues/2507
An option is added @rpgdev! :)

**Comment by rpgdev** [comment]
I just updated it, looking at the output of `spicetify config` looks like the option is false for me right now. Hopefully I won't see that button again but even if I do now I know the right project to post the issue ;)

Thanks @Daksh777!
