### ISSUE TITLE
Can't install spotify using the auto installer

### ISSUE THREAD

**Issue by 87LittleDragon** [Daksh777/SpotifyNoPremium#109]
I got this error `Move-Item : Cannot find path 'C:\Users\gavin\Downloads\temp\SpotifyNoPremium' because it does not exist.`

I am on Windows 10.

**Comment by Tresillo2017** [comment]
Try this in powershell https://github.com/Daksh777/SpotifyNoPremium?tab=readme-ov-file#windows

**Comment by Daksh777** [comment]
Hey @87LittleDragon, do you still need help?
(PS. Thank you @Tresillo2017 for helping them out)
