### ISSUE TITLE
theme-install.ps1 trying to find files that doesn't exists

### ISSUE THREAD

**Issue by SapitoSucio** [Daksh777/SpotifyNoPremium#11]
I tried to install this but when I try to backup apply it throws me this error:
![image](https://user-images.githubusercontent.com/7357354/125482910-623c5db1-58e7-4b2b-8dd5-65acb81ff641.png)

If I go to the location I can't seem to find the Spotify folder

Spotify Version 1.1.62.583.gdac868ed-a

**Comment by Daksh777** [comment]
Hey,

Can you go to `C:\Users\USERNAME\.spicetify` and find the `config-xpui.ini` file? If yes, add the location `C:\Users\Daksh\USERNAME\Roaming\Spotify\prefs` to `prefs_path` and save it. (Also verify if `prefs` exist in `C:\Users\USERNAME\AppData\Roaming\Spotify\prefs`)
If that doesn't work, try reinstalling Spicetify.

**Comment by SapitoSucio** [comment]
Thank you, I solved it

This is how it worked for me

![image](https://user-images.githubusercontent.com/7357354/125891499-8f6b2eac-565f-4927-b4e3-412df8248b11.png)


But then I got #13 'd

**Comment by ElReyCoraje** [comment]
> I tried to install this but when I try to backup apply it throws me this error:
> ![image](https://user-images.githubusercontent.com/7357354/125482910-623c5db1-58e7-4b2b-8dd5-65acb81ff641.png)
> 
> If I go to the location I can't seem to find the Spotify folder
> 
> Spotify Version 1.1.62.583.gdac868ed-a

bro do you mind helping me ? I have the same problem

**Comment by Daksh777** [comment]
Hey @ElReyCoraje,

Please read my previous comment
> Please make sure that you are NOT running the script as admin. 
>
> Then go to `C:\Users\USERNAME\.spicetify` and check if you can find the `config-xpui.ini` file.
> If yes, add the location `C:\Users\Daksh\USERNAME\Roaming\Spotify\prefs` to `prefs_path` and save it. (Also verify if  the file `prefs` exist in `C:\Users\USERNAME\AppData\Roaming\Spotify\prefs`)

**Comment by Daksh777** [comment]
I will look into it and check if I can do something with the script for users running in the administrative profile.
