### ISSUE TITLE
Audio Ads!

### ISSUE THREAD

**Issue by ankur-raikwar** [Daksh777/SpotifyNoPremium#110]
### Bug

**30 seconds Audio ads** _(only)_ **when song ends.**

### First appeared on

**After latest Spotify update, i.e 28 September.**

### Notes

**1. Ads are not showing in between songs.
2. There are 2 ads showing each of 30 seconds, after a song ends.**

### Spotify / Spicetify Version Info

**Spotify for Windows (64 bit)
1.2.21.1104.g42cf0a50
Spicetify v2.24.2
Theme: SpotifyNoPremium
Extensions: adblock.js
Custom apps:**

### More Details
_**See the attached Screenshots to have an idea what is exactly happening.**_ 

![Screenshot (34)](https://github.com/Daksh777/SpotifyNoPremium/assets/3439247/d5ee173a-b7e2-4dbd-83a8-01bd930311ad)
![Screenshot (37)](https://github.com/Daksh777/SpotifyNoPremium/assets/3439247/7ff9df3b-f4a6-4f41-8428-5cf8462542aa)

**Comment by Pein1911** [comment]
it seems need a adblock update. I got a "spotify not reponse" messenger at the end of update command too

**Comment by Daksh777** [comment]
I've updated the adblock extension, could you please run the update script and try again?

**Comment by ankur-raikwar** [comment]
I've listened for half an hour, **ads are no more**!
Issue can be closed now.

_Here is log of_ **update.bat**

![Screenshot 2023-10-02 163644](https://github.com/Daksh777/SpotifyNoPremium/assets/3439247/a488bde3-66ea-4fcc-b2e1-edd13a05224b)

**Comment by Daksh777** [comment]
That's awesome! :)
I'l close this issue then
