### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Kunvar-Singh** [Daksh777/SpotifyNoPremium#111]
The problem arose today when I started getting audio ads after a few songs. I thought that spicetify stopped working after the last update. So, I proceeded to reinstall using the install.bat and clicking yes when it asked if spicetify is already installed. After this it all went downhill. I started getting errors like access to path is denied or spotifynopremium not found or even cannot find path because it doesn't exist. And now the setup is picking the path of the setup location itself, no matter where I store it. I have tried installing it from the folder in appdata but then it just crashes after a few seconds. I have tried applying a backup, downloading a new setup and even installing manually

**Comment by Daksh777** [comment]
Hey Kunvar!
Could you please tell what error you're getting on using the `install.bat` file?

**Comment by ankur-raikwar** [comment]
@Kunvar-Singh 

You can try uninstalling 'Spicetify' and make clean install (run install.bat). I suggest reinstalling Spotify as well.
 

1. **Uninstalling spicetify (execute below commands one by one in powershell):**

- `spicetify restore`
- `rmdir -r -fo $env:APPDATA\spicetify`
- `rmdir -r -fo $env:LOCALAPPDATA\spicetify`

2. **Uninstall Spotify & re-install using one of the links below (only choose X64 if you are using 64 bit Windows):**

 > x86      https://download.scdn.co/SpotifyFullSetup.exe

 > x64      https://download.scdn.co/SpotifyFullSetupX64.exe


3. **Now run install.bat!**

4. **Still not working ? post error logs/output! here**

**Comment by Kunvar-Singh** [comment]
> @Kunvar-Singh
> 
> You can try uninstalling 'Spicetify' and make clean install (run install.bat). I suggest reinstalling Spotify as well.
> 
> 1. **Uninstalling spicetify (execute below commands one by one in powershell):**
> 
> * `spicetify restore`
> * `rmdir -r -fo $env:APPDATA\spicetify`
> * `rmdir -r -fo $env:LOCALAPPDATA\spicetify`
> 
> 2. **Uninstall Spotify & re-install using one of the links below (only choose X64 if you are using 64 bit Windows):**
> 
> > x86      https://download.scdn.co/SpotifyFullSetup.exe
> 
> > x64      https://download.scdn.co/SpotifyFullSetupX64.exe
> 
> 3. **Now run install.bat!**
> 4. **Still not working ? post error logs/output! here**

This what I get
<img width="960" alt="Screenshot 2023-10-02 222310" src="https://github.com/Daksh777/SpotifyNoPremium/assets/85383360/0e663025-944f-4adb-8be2-4fd4668e214c">

**Comment by Kunvar-Singh** [comment]
> Hey Kunvar! Could you please tell what error you're getting on using the `install.bat` file?

This is the error I'm getting and the path location changes depending on where I'm running the setup from.
<img width="960" alt="Screenshot 2023-10-02 222547" src="https://github.com/Daksh777/SpotifyNoPremium/assets/85383360/4ca96aa0-ea2a-4356-ab50-728305fbc26b">
<img width="960" alt="Screenshot 2023-10-02 222515" src="https://github.com/Daksh777/SpotifyNoPremium/assets/85383360/f7cec93f-2814-4ecf-9636-7de21d1257e6">

**Comment by ankur-raikwar** [comment]
@Kunvar-Singh

I think what you did was you ran batch file as admin, for installing (install.bat), and now trying to uninstalling it as **User Prompt**.
It won't work that way. Correct me if I am wrong here. 

**So what I suggest now is to** `Open Powershell/Terminal` **as admin** **and try uninstalling spicetify.**

**If this still fails, then you can manually remove directory `C:\Users\Name\AppData\Local\spicetify` (try unlocker tool if needed) and remove environment variable from System Properties. See attached screenshot for help.**

![Screenshot 2023-10-03 145902](https://github.com/Daksh777/SpotifyNoPremium/assets/3439247/e134cb77-eb2f-4eac-a35c-dcfeea78ee74)

**Comment by Kunvar-Singh** [comment]
> @Kunvar-Singh
> 
> I think what you did was you ran batch file as admin, for installing (install.bat), and now trying to uninstalling it as **User Prompt**. It won't work that way. Correct me if I am wrong here.
> 
> **So what I suggest now is to** `Open Powershell/Terminal` **as admin** **and try uninstalling spicetify.**
> 
> **If this still fails, then you can manually remove directory `C:\Users\Name\AppData\Local\spicetify` & `C:\Users\Name\AppData\Roaming\spicetify` (try unlocker tool if needed) and remove environment variable from System Properties. See attached screenshot for help.**
> 
> ![Screenshot 2023-10-03 145902](https://user-images.githubusercontent.com/3439247/272215987-e134cb77-eb2f-4eac-a35c-dcfeea78ee74.jpg)

Hey, thanks for the help. I did as you said and it's working now. However, I remember installing without admin because when I tried installing with admin, I got a pop-up saying admin was not needed and that I should retry again as non-admin to avoid future problems.
Anyway, It's working now and that's what matters. Thanks again
