### ISSUE TITLE
access denied error

### ISSUE THREAD

**Issue by Cloudyxz** [Daksh777/SpotifyNoPremium#112]
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/89943889/691cca72-c279-471a-a1c8-4059fc506820)
 help w this error? how to allow access

**Comment by OnlyKaz** [comment]
Try updating with admin permissions, if doesn't work, i don't know then.

**Comment by Daksh777** [comment]
Do you happen to have some antivirus which is blocking the permissions?
Like @OnlyKaz said, try running the script as an admin and let us know how it goes

**Comment by Cloudyxz** [comment]
yes i turned it off and it worked thx
