### ISSUE TITLE
Dark overlay making spotify unusable from time to time

### ISSUE THREAD

**Issue by rpgdev** [Daksh777/SpotifyNoPremium#117]
I'm getting a dark overlay over spotify from time to time.. you might need to update the adblock.js script in this extension.

**Comment by TuanMaiz** [comment]
press esc and you should be fine

**Comment by rpgdev** [comment]
@TuanMaiz I'll keep it in mind next time it shows up but I manually updated the adblock script and it hasn't shown up again.

**Comment by etsongrey** [comment]
Would you share the edit of the adblock script here @rpgdev ?

**Comment by rpgdev** [comment]
> Would you share the edit of the adblock script here @rpgdev ?

It's not an edit, I simply replaced it with the updated version from upstream but actually, the gray overlay still showed up afterwards (sigh) now I'm using @TuanMaiz suggestion.

**Comment by Daksh777** [comment]
Sorry for the delay!
I'll have a look at the issue and see what can be done, meanwhile, you can also keep an eye on the main repo's issues:
https://github.com/CharlieS1103/spicetify-extensions/issues/102
https://github.com/CharlieS1103/spicetify-extensions/issues/80

**Comment by rpgdev** [comment]
@Daksh777 No worries, thanks for keeping this project alive. It makes a difference!

**Comment by Daksh777** [comment]
Hey @rpgdev, the ad block has been updated so do check it out
Hopefully, there shouldn't be this issue now.
