### ISSUE TITLE
backups 

### ISSUE THREAD

**Issue by 18deaths** [Daksh777/SpotifyNoPremium#119]
can i get instructions on how to do this shit
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/136187805/2bd7f2ef-85b9-4241-a869-b204de7b5b5e)

**Comment by Daksh777** [comment]
Hey @18deaths

Sorry for the delay. Are you updating the app?
Please run `spicetify restore backup` and then `spicetify backup` in Powershell, like it is printed in the console, and then you can run the update/install scripts.

**Comment by Daksh777** [comment]
I'm closing this issue as it's been inactive for a while.
Let me know if you need further help by reopening this.
