### ISSUE TITLE
git : The term 'git' is not recognized

### ISSUE THREAD

**Issue by RenRenIsWeird** [Daksh777/SpotifyNoPremium#12]
Is there something I did wrong here? I installed the full script

![Capture](https://user-images.githubusercontent.com/56497824/125715939-13e43c8e-c017-42e0-b470-b0093c085482.PNG)

**Comment by Daksh777** [comment]
Hi there,

The script should've opened a new browser window to go to the Git downloads website. You had to download and install the .exe file and then continue running the script. Could you confirm a browser window was opened and the Git download page was loaded?

**Comment by RenRenIsWeird** [comment]
Yep, a window to Git download page was opened and I downloaded and installed the Git.exe

**Comment by Daksh777** [comment]
Oh, I think it's because the shell/terminal needs a restart before actually recognizing Git as a command. Could you launch a new terminal window and see if `git` returns anything?

**Comment by RenRenIsWeird** [comment]
Relaunching the new terminal and command worked, but the Spotify is stucked on this screen

![Capture](https://user-images.githubusercontent.com/56497824/125739627-68ae690a-fbf4-46fc-a075-17dba40f9648.PNG)

**Comment by Daksh777** [comment]
Okay, I will figure out what to do with Git installation.
Also, that blank screen is because of a bug in Spicetify itself, see https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-880459337

**Comment by RenRenIsWeird** [comment]
So, I have to downgrade Spotify, disable auto-update, and run the command again?

**Comment by Daksh777** [comment]
Yes, you can run `theme-install.ps1` since Git is already installed in your system.

**Comment by Daksh777** [comment]
https://github.com/Daksh777/SpotifyNoPremium/commit/731bf2ca727648876b41e33f082537eeb04717b5 should fix this problem.

**Comment by RenRenIsWeird** [comment]
It worked now, thank you for helping me!
