### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by devjoseq** [Daksh777/SpotifyNoPremium#120]
Hello, I got this error while installing
![Screenshot 2024-03-23 221959](https://github.com/Daksh777/SpotifyNoPremium/assets/136089315/968f81f6-9bbd-4ab6-b327-6c3a88086ba4)

**Comment by Daksh777** [comment]
It seems like you clicked on skip installation of Spicetify (not Spotify) and you don't have Spicetify already installed. You can re run the script and select no when it asks for Spicetify installation, that should work

**Comment by devjoseq** [comment]
At this stage, when I press any key, the terminal immediately closes and nothing happens.
![Uploading Screenshot 2024-03-25 230545.png…]()

**Comment by Daksh777** [comment]
It seems like the screenshot wasn't uploaded
Can you add the screenshot again?

**Comment by devjoseq** [comment]
sorry, it's here
![Screenshot 2024-03-25 230545](https://github.com/Daksh777/SpotifyNoPremium/assets/136089315/10a773a7-9eed-4acb-a3ba-a0735cead359)

**Comment by Daksh777** [comment]
Did you click on cancel on the popup asking if Spicetify (not Spotify) was already installed?

**Comment by devjoseq** [comment]
yes i was clicked

**Comment by devjoseq** [comment]
I fixed this error, thank you

**Comment by Daksh777** [comment]
I'm glad that it was fixed, can you tell what was the fix?
That would help anyone else to fix the issue if they're facing the same error

**Comment by devjoseq** [comment]
I don't think this will happen to others, because I am using a modified W10 and the problem was something related to this.
