### ISSUE TITLE
cant install 

### ISSUE THREAD

**Issue by saeedbk500** [Daksh777/SpotifyNoPremium#121]
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/157381688/d27d6b2f-308f-4762-9340-061868ea52d3)

**Comment by Daksh777** [comment]
You have the Microsoft Store version of Spotify. Can you uninstall that version and download Spotify from https://www.spotify.com/us/download/windows/ and let me know if it works?

**Comment by saeedbk500** [comment]
it worked, thank you alot, ReSpEcCcC
