### ISSUE TITLE
lyrics still have a pop up

### ISSUE THREAD

**Issue by bulieme** [Daksh777/SpotifyNoPremium#123]
spotify version: idk pls tell me how to see that

![me opening a lyrics tab](https://github.com/Daksh777/SpotifyNoPremium/assets/53142287/61b65dbd-ab38-4ecd-b1c1-6c5b5d7d24a4)

**Comment by Pein1911** [comment]
adblock need a update too

**Comment by bulieme** [comment]
> adblock need a update too

they said it was serverside so we cant actually bypass this at the moment

**Comment by Mubelotix** [comment]
> > adblock need a update too
> 
> they said it was serverside so we cant actually bypass this at the moment

We can load lyrics from another server than Spotify's

**Comment by Mubelotix** [comment]
Lyrics appear to be highly copyrighted but there is nothing to prevent us from running speech-to-text models on the audio
