### ISSUE TITLE
Suggestion - Remove "Download Playlist" in a playlist

### ISSUE THREAD

**Issue by Stabnormality** [Daksh777/SpotifyNoPremium#14]
![image](https://user-images.githubusercontent.com/64324595/127735281-a43a4e21-ab58-4760-9632-c241e5c51d90.png)
remove the circled items as they are unable to be used without premium.

**Comment by fosam** [comment]
I'm new to this theme, i want to make some customizations too but how do you find which elements to edit? and how do you edit them?

**Comment by Daksh777** [comment]
@Stabnormality I won't merge the PR for now, I'll look into the issue and see if there's another way to hide the download item from the menu without grabbing the element.

**Comment by Daksh777** [comment]
> I'm new to this theme, i want to make some customizations too but how do you find which elements to edit? and how do you edit them?

You can execute `spicetify enable-devtool` to enable Chrome developer tools. You can then open the developer tools menu by pressing `Ctrl+Shift+I` and start working with styles.
However, a bit of experience with Chrome dev tools and/or CSS will help a lot.

**Comment by Daksh777** [comment]
@system32uwu Could you perhaps help me with this if you have any idea?
It's not possible to use regex to grab the text. Using the `span` class instead doesn't work either because that class is used in other items of the menu too.

**Comment by fosam** [comment]
> > I'm new to this theme, i want to make some customizations too but how do you find which elements to edit? and how do you edit them?
> 
> You can execute `spicetify enable-devtool` to enable Chrome developer tools. You can then open the developer tools menu by pressing `Ctrl+Shift+I` and start working with styles.
> However, a bit of experience with Chrome dev tools and/or CSS will help a lot.

@Daksh777 Yeah Thanks, i thought there was another method because Spicetify still has a bug and is not working with the latest Spotify.

**Comment by system32uwu** [comment]
> 
> 
> @system32uwu Could you perhaps help me with this if you have any idea?
> It's not possible to use regex to grab the text. Using the `span` class instead doesn't work either because that class is used in other items of the menu too.

Sorry I'm late to this, I took the day off yesterday. What you ended up doing looks good to me!

**Comment by Daksh777** [comment]
> Sorry I'm late to this, I took the day off yesterday. What you ended up doing looks good to me!

Sorry for the ping and thank you for confirming that.
