### ISSUE TITLE
Fatal error while updating theme from GitHub

### ISSUE THREAD

**Issue by francescoaracu** [Daksh777/SpotifyNoPremium#16]
When using update.ps1 script with PowerShell, the first step leads to a fatal error.
![image](https://user-images.githubusercontent.com/48188510/129533497-2e83bbe0-57a3-4b9a-a6e6-ebda88b13aaa.png)

**Comment by Daksh777** [comment]
Are you sure you ran [install.ps1](https://gitcdn.link/repo/Daksh777/SpotifyNoPremium/main/install.ps1) script before? If not, please run install.ps1 script.

**Comment by francescoaracu** [comment]
> Are you sure you ran [install.ps1](https://gitcdn.link/repo/Daksh777/SpotifyNoPremium/main/install.ps1) script before? If not, please run install.ps1 script.

Thanks a lot, I didn't run the install script because I already had Git installed and also Spicetify (latest version).

**Comment by Daksh777** [comment]
I apologize for the confusing README, I'll rephrase it so that it's more clear.
