### ISSUE TITLE
Fatal Error - fatal-error.button-label

### ISSUE THREAD

**Issue by zachjmurphy** [Daksh777/SpotifyNoPremium#17]
I'm getting a error-dialog.generic.header (fatal-error.button-label) issue now on the latest spotify version
![image](https://user-images.githubusercontent.com/78761892/130370056-c941804e-72e4-48df-b114-5ae5cf7c3f95.png)

**Comment by Daksh777** [comment]
Which version of Spotify are you using?

**Comment by zachjmurphy** [comment]
The latest Spotify version. I can’t check what Spotify version I am using because of that error.

**Comment by Daksh777** [comment]
Okay. I uninstalled Spotify and deleting Spicetify and ran the [install.bat](https://gitcdn.link/repo/Daksh777/SpotifyNoPremium/main/install.bat) script and it worked completely fine for me.

Could you perhaps try uninstalling Spotify and deleting the `.spicetify` folder in `C:\Users\USERNAME` and then installing Spotify and running the [install.bat](https://gitcdn.link/repo/Daksh777/SpotifyNoPremium/main/install.bat) script?

**Comment by zachjmurphy** [comment]
Okay, I will try those steps

**Comment by zachjmurphy** [comment]
Okay, following those steps seemed to have fixed the issue.

**Comment by Daksh777** [comment]
That's great! I'll close the issue.
