### ISSUE TITLE
I can't apply the patch on Win 11

### ISSUE THREAD

**Issue by SapitoSucio** [Daksh777/SpotifyNoPremium#24]
UPDATE: It was my fault, I didn't put /prefs at then end of prefs_path :( -- All working flawlessly

I have used this tool several times already, with some problems but nothing I couldn't figure ou, at least until now :(

I have upgraded my pc to Win 11 and I just tried to apply the SpotifyNoPremium theme and it throws me this 

![image](https://user-images.githubusercontent.com/7357354/135949664-b2871df6-0346-41a7-aa20-4e4017fde7bf.png)
It's in Spanish, and it says "Controller not valid"

The installation is marked as successful and proceeds to ask me if I want to install BlockTheSpot, I click yes and then Spotify opens, but the SpotifyNoPremium theme was not successfully applied to it

![image](https://user-images.githubusercontent.com/7357354/135950272-09c82df1-a7b7-452d-b74c-9f643af08566.png)

**Comment by Daksh777** [comment]
Great to hear that you figured it out, I'll close this issue.
