### ISSUE TITLE
SpotifyAB Path Error

### ISSUE THREAD

**Issue by realjameswolf** [Daksh777/SpotifyNoPremium#28]
Every time I try to install the patch, this happen,
I want to emphasize that I do not have spotify installed from microsoft store
![image](https://user-images.githubusercontent.com/93506322/139623963-620bba19-f1d4-4e0d-881c-5fcb84de98aa.png)

**Comment by Daksh777** [comment]
> I want to emphasize that I do not have spotify installed from microsoft store

Are you sure? Spotify's non-Microsoft Store variant will install in `C:/Users/NAME/Local/Spotify` and not in `C:/Users/NAME/Local/Packages` (this is the location where Microsoft Store packages are downloaded)

Can you uninstall the current Spotify app and download it from https://spotify.com/download and see if that helps?

**Comment by realjameswolf** [comment]
Delete any cache files that were in packages on SpotifyAB and anywhere, reinstall everything again and the patch worked correctly, thanks!

**Comment by PimenTV** [comment]
I have the same problem but i dont have the folder SpotifyAB in Packages
![image](https://user-images.githubusercontent.com/84513463/186401193-5f05c0c8-8f48-4b83-8409-7a179feb77fb.png)

**Comment by Daksh777** [comment]
Hi there @PimenTV, so sorry for the late reply.
Please go to `%appdata%\spicetify` and edit the following highlighted entries according to your username:
![image](https://user-images.githubusercontent.com/43648146/187505683-46d7d22f-409e-4bdf-ab37-69935dc2b06a.png)

**Comment by PimenTV** [comment]
Thanks you so much, thats works!!
