### ISSUE TITLE
Add a requirement info

### ISSUE THREAD

**Issue by Rajbir98** [Daksh777/SpotifyNoPremium#30]
Add the requirement of windows PowerShell 5 for lower version of windows

**Comment by Daksh777** [comment]
By default Windows 7 comes with PowerShell version 2.0 installed.
The simplest solution is to upgrade your version of PowerShell to version 5.1. 
You can do that by downloading the Windows Management Framework: https://www.microsoft.com/en-us/download/details.aspx?id=54616
