### ISSUE TITLE
Spotify looks strange

### ISSUE THREAD

**Issue by mizzunet** [Daksh777/SpotifyNoPremium#36]
![image](https://user-images.githubusercontent.com/10193999/145943495-993eef06-140e-4fab-af05-c1cf00a8c233.png)

This how Spotify looks like once the theme is applied.
```
spicetify config
Settings
spotify_path                  /opt/spotify
current_theme                 SpotifyNoPremium
color_scheme                  
replace_colors                1
overwrite_assets              0
check_spicetify_upgrade       0
prefs_path                    /home/missu/.config/spotify/prefs
inject_css                    1
spotify_launch_flags          

Preprocesses
remove_rtl_rule               1
expose_apis                   1
disable_upgrade_check         1
disable_sentry                1
disable_ui_logging            1

AdditionFeatures
home_config                   1
experimental_features         1
extensions                    fullAppDisplay.js
                              keyboardShortcut.js
custom_apps
sidebar_config                1
```

Spotify version: 1:1.1.72.439-3

Arch Linux

**Comment by Daksh777** [comment]
Are you sure you haven't modified this theme? I'm not using any custom colors that would cause this problem.
Also, it seems like you are on an old Spotify version, please update it and try again.

**Comment by mizzunet** [comment]
> Are you sure you haven't modified this theme? I'm not using any custom colors that would cause this problem.

Yes. I have even tried deleting old folder and cloning it again.

> Also, it seems like you are on an old Spotify version, please update it and try again.

Oh, it's latest AUR package https://aur.archlinux.org/packages/spotify/. I'm not sure if it's the latest Spotify

**Comment by Daksh777** [comment]
Are you using vanilla Arch Linux or any other Arch-based distro? I'll try to test it in a VM

**Comment by mizzunet** [comment]
I'm on vanilla Arch.

**Comment by Daksh777** [comment]
Sorry for the delay, I'm having a hard time installing Arch on a VM.
I'll test it and let you know in a few days more.

**Comment by Daksh777** [comment]
Hi, I'm really sorry for the late reply.
I installed Spotify on Manjaro since Arch was not working on my VM and everything worked normally.

Could you try removing the extensions and check if that helps?

**Comment by mizzunet** [comment]
After reinstalling Spotify and spicetify, it works. 

I'm not sure why it didn't back then.
Anyway thanks
