### ISSUE TITLE
Seems to not work anymore?

### ISSUE THREAD

**Issue by iGameEveryDay6** [Daksh777/SpotifyNoPremium#37]
I'm not sure of I'm doing something wrong but for some reason this doesn't seem to work anymore. The ads are being blocked but the UI still has the upgrade button and the ad placeholder in the playlists.

**Comment by Daksh777** [comment]
Apologies for the late reply and Merry Christmas!

Could you tell what's your Spotify version?

**Comment by iGameEveryDay6** [comment]
Merry Christmas to you as well! 
My Spotify version is 1.1.74.631.g0b24d9ad. (Sorry, I wasn't sure if the letters at the end were needed so I put them anyway.)

**Comment by Daksh777** [comment]
Can you open a terminal and type `spicetify enable-devtool` and then check what's the class name of that element by opening the dev tools (`Ctrl`+`Shift`+`I`)?
![Video](https://user-images.githubusercontent.com/43648146/147466437-4230ec17-cdef-437d-bedc-a7cc4c8d25da.mp4)

**Comment by iGameEveryDay6** [comment]
Alright. That's the class name: 
![image](https://user-images.githubusercontent.com/83013894/147480009-fafbda1f-f293-442b-983e-7ec9bba1d032.png)

**Comment by Daksh777** [comment]
That's weird because that class is already being hidden
https://github.com/Daksh777/SpotifyNoPremium/blob/32aaf9ebc80d83dc07546e94f9cf0dd76ae0c797/user.css#L8-L11

Are you sure the theme is applied correctly? Can you go to `C:\Users\YOURNAME\.spicetify` and send the contents of `config-xpui.ini`? Also, can you run the `update.bat` file in `C:\Users\YOURNAME\.spicetify\Themes\SpotifyNoPremium` and see if that helps?

**Comment by iGameEveryDay6** [comment]
These are the contents of my `config-xpui.ini` file:
```
[Setting]
current_theme           = SpotifyNoPremium
color_scheme            = 
replace_colors          = 0
overwrite_assets        = 1
spotify_path            = C:\Users\Ivan\AppData\Roaming\Spotify
prefs_path              = C:\Users\Ivan\AppData\Roaming\Spotify\prefs
inject_css              = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
custom_apps           = lyrics-plus|reddit|new-releases
sidebar_config        = 1
home_config           = 1
experimental_features = 1
extensions            = bookmark.js|fullAppDisplay.js|shuffle+.js|copyPlaylist.js|historyShortcut.js|webnowplaying.js

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.74.631.g0b24d9ad
with    = 2.8.3
```
Also I did try using `update.bat` many times but that did not fix my problem.

**Comment by Daksh777** [comment]
Can you try removing all the extensions and custom apps just to confirm if it's them causing the issue?

**Comment by iGameEveryDay6** [comment]
I tried and it looks like I'm having the same issue.

**Comment by Daksh777** [comment]
This is weird.
Can you verify if the `user.css` file is present in the `Sources` tab of the developer tools? If yes, can you verify whether the contents CSS selectors for the new version are present?
![image](https://user-images.githubusercontent.com/43648146/147561779-f2157cf2-38c6-4162-b0ac-772ade08dbe8.png)

**Comment by iGameEveryDay6** [comment]
For some reason it looks like it's empty.

**Comment by iGameEveryDay6** [comment]
I think I've done something wrong, but I don't know what.

**Comment by Daksh777** [comment]
I think the best thing to try right now would be to uninstall Spicetify and Spotify and install Spotify again and finally run `install.bat`

**Comment by iGameEveryDay6** [comment]
Alright. I'll try.

**Comment by iGameEveryDay6** [comment]
Just did that. It looks like it worked this time.

**Comment by Daksh777** [comment]
That's great, I'll close this issue then.
