### ISSUE TITLE
discord integration not working

### ISSUE THREAD

**Issue by VelamyGH** [Daksh777/SpotifyNoPremium#38]
not sure why but ive tried tweaking with experimental settings, reinstalling, connecting and disconnecting my account and i cant seem to get discord to recognize whats playing on the desktop app

**Comment by Daksh777** [comment]
Can you confirm if it works on non-modified Spotify app?

**Comment by VelamyGH** [comment]
how exactly would i ensure that every modification is removed

**Comment by VelamyGH** [comment]
update, got it to work. was an error with something in my hosts file
