### ISSUE TITLE
Home page not loading

### ISSUE THREAD

**Issue by notpbj** [Daksh777/SpotifyNoPremium#4]
Hi! I just installed SpotifyNoPremium and the home page is no longer [loading](https://i.imgur.com/CRt5SGS.png)
Spotify ver 1.1.61.583.gad060c66-a

**Comment by Daksh777** [comment]
Could you try reinstalling the Spotify app?

**Comment by system32uwu** [comment]
@notpbj this might happen when you apply themes without closing Spotify first. Also is your spotify from the Microsoft Store? We should mention that it won't work if it's Spotify from the MS Store.

**Comment by notpbj** [comment]
Reinstalling did not change anything.... It still doesn't load. Spotify was installed from the official website, not from ms store. Spotify was closed when applying the theme

**Comment by system32uwu** [comment]
So, you had Spotify opened and you did run [theme-install.ps1](https://github.com/Daksh777/SpotifyNoPremium/blob/main/theme-install.ps1)? Maybe it being opened as you were installing broke something, try removing Spotify and spicetify and deleting %USERPOFILE%/.spicetify, and installing everything once again (with Spotify closed).

**Comment by notpbj** [comment]
I did the manual installation though

**Comment by system32uwu** [comment]
What does manual installation mean exactly? That you didn't use the scripts provided? In that case please post what commands you used.

Steps:

in $HOME/.spicetify/Themes:
```
git clone https://github.com/Daksh777/SpotifyNoPremium/
spicetify config current_theme SpotifyNoPremium color_scheme base
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply
```

**Comment by notpbj** [comment]
These are the commands I used:
`cd "$(spicetify -c | Split-Path)\Themes"`
`git clone https://github.com/Daksh777/SpotifyNoPremium`
`spicetify config current_theme SpotifyNoPremium`
`spicetify apply`

**Comment by notpbj** [comment]
I'm getting this error when running either of the .ps1 files:
`error Cannot open file C:\Users\PBJ\.spicetify\Themes\SpotifyNoPremium\color.ini`

**Comment by Daksh777** [comment]
> I'm getting this error when running either of the .ps1 files:
> `error Cannot open file C:\Users\PBJ\.spicetify\Themes\SpotifyNoPremium\color.ini`

Can you check if the `SpotifyNoPremium` folder is present in `C:\Users\PBJ\.spicetify`? If yes, make sure that all the contents are there in the folder just like the contents in GitHub.
Also, can you please give your Spotify and Spicetify version?

**Comment by notpbj** [comment]
Ok basically I deleted *username*\.spicetify\SpotifyNoPremium and then wrote those commands and it worked

**Comment by system32uwu** [comment]
Nice! The files were probably just misplaced then.

**Comment by notpbj** [comment]
Yeah I guess. Thanks for the help!
