### ISSUE TITLE
New Spotify Update Breaks Hide Upgrade Button Feature

### ISSUE THREAD

**Issue by Rajbir98** [Daksh777/SpotifyNoPremium#41]
![image](https://user-images.githubusercontent.com/84771149/150639914-077b0c54-068f-4c9e-94e7-d12cec634b00.png)

OS: Windows v6.1.7601
Spotify: v1.1.77.643
Spicetify: v2.8.4
SpotifyNoPremium: v1.66

**Comment by Daksh777** [comment]
I'm on the same as yours (1.1.77.643.g3c4c6fc6) and I do not see any ads. Can you post the entire Spotify version?
Also, are you sure you're running the latest version of the theme?

**Comment by Rajbir98** [comment]
and I got this problem when I booted Spotify it prompted installing Spotify so later I update spicetify dribblish theme and Spotify no premium but after that Spotify update the upgrade button comes
well I run update.bat before this issue

**Comment by Rajbir98** [comment]
well i will try to reinstall spotify then let u know

**Comment by Rajbir98** [comment]
reinstalling Spotify fixes the problem
