### ISSUE TITLE
Remove premium section in the tabs of Spotify.

### ISSUE THREAD

**Issue by IamNickerson** [Daksh777/SpotifyNoPremium#42]
Hey,
Is it possible to remove also the premium tab section which is appearing in the section tab of Spotify.
![image](https://user-images.githubusercontent.com/61643704/152994201-0fed8e2c-5a52-402a-af17-d69ba0e37503.png)

**Comment by Daksh777** [comment]
Can you please tell me what do you mean by "tab section"? Maybe if you could upload a screenshot of the entire window which shows that?

**Comment by IamNickerson** [comment]
Can you try removing this I circled what to remove
![image](https://user-images.githubusercontent.com/61643704/153017645-3969349f-292d-439c-81ba-10eba3fbb395.png)

**Comment by IamNickerson** [comment]
This came on the Spotify version 1.1.78.765

**Comment by Daksh777** [comment]
![image](https://user-images.githubusercontent.com/43648146/153033628-f5feb5d0-ece3-4806-b1e0-0c85e4dbc1c7.png)
I do not see this, could you perhaps try restoring Spotify to the stock version and tell if it's still present?

**Comment by IamNickerson** [comment]
How do I restore Spotify?

**Comment by IamNickerson** [comment]
Is it possible to give a Css script to remove it?

**Comment by Daksh777** [comment]
You have to run `spicetify restore` in a terminal (like CMD or Powershell) and that will restore Spotify.

**Comment by IamNickerson** [comment]
Okay

**Comment by IamNickerson** [comment]
Oh yeah it is not there.

**Comment by IamNickerson** [comment]
Is there anyway to remove it?

**Comment by Daksh777** [comment]
So it's a problem with the theme you're using. You need to open an issue in the particular theme's repo.

**Comment by IamNickerson** [comment]
I have to check the code of theme
Like the User.css

**Comment by IamNickerson** [comment]
Ok i have to find out

**Comment by IamNickerson** [comment]
> So it's a problem with the theme you're using. You need to open an issue in the particular theme's repo.

I mean i tried a other theme which is Glaze and still it is showing the premium section tab Look
![image](https://user-images.githubusercontent.com/61643704/153209018-71e843bd-50ac-4ee0-ab90-3553c0566372.png)

**Comment by IamNickerson** [comment]
> So it's a problem with the theme you're using. You need to open an issue in the particular theme's repo.

They aren't responsible of this I mean u can just make a code about it.

**Comment by IamNickerson** [comment]
I will still in fact make an issue in spicetify themes about this.

**Comment by IamNickerson** [comment]
But I think it is not issue with them.

**Comment by Daksh777** [comment]
> They aren't responsible of this I mean u can just make a code about it.

I won't be able to do it since I personally don't see it on my client.
And since you're using someone else's theme and not this one, you should contact the respected owner of that theme to help you with the issue.

**Comment by IamNickerson** [comment]
But this is happening to all people who are having themes then I tried a another theme and still it is showing that I would like you to try out a theme with spotifynopremium and see it if shows.

**Comment by IamNickerson** [comment]
How should say it to them? the issue?

**Comment by Daksh777** [comment]
> But this is happening to all people who are having themes then I tried a another theme and still it is showing that I would like you to try out a theme with spotifynopremium and see it if shows.

Makes sense. I'll try clean installing Spicetify and Spotify and see if it shows for me since it is not visible to me as of now.

> How should say it to them? the issue?

You can attach the screenshot and request them to hide/remove that element.

**Comment by Daksh777** [comment]
Update: I do not see that tab even on the stock Spotify app
![image](https://user-images.githubusercontent.com/43648146/153596158-10b0378e-a813-4611-9a78-2aeb7d3cae0c.png)

I wouldn't be able to help you if I can't reproduce it on my end

**Comment by IamNickerson** [comment]
Does Spotifynopremium work with themes?

**Comment by IamNickerson** [comment]
Try a theme out with Spotifynopremium because it would show.

**Comment by Daksh777** [comment]
I'm sorry, I don't understand what you are trying to say. Can you please elaborate?

**Comment by IamNickerson** [comment]
Just try a spicetify theme with spotifynopremium

**Comment by IamNickerson** [comment]
And tell if it is showing the premium thingy.

**Comment by Daksh777** [comment]
Can you please send the link of the theme which you were using? That'd be much better.

**Comment by IamNickerson** [comment]
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Sleek

**Comment by IamNickerson** [comment]
The theme I used was sleek.

**Comment by Daksh777** [comment]
Okay, let me check.

**Comment by IamNickerson** [comment]
How

**Comment by IamNickerson** [comment]
Ok let me try reinstall Spotifynopremium since there is some fix u did.

**Comment by IamNickerson** [comment]
Hey it worked I fixed the issue which was actually happening the User.css file basically I put the user.css code of spotifynopremium  on User.css in sleek which caused that to happen so fixed it and now everything is fine but now it is appearing on the context menu when click on pfp and right now I am finding where is the issue coming.

**Comment by IamNickerson** [comment]
Ok done fixing with the context menu upgrade thingy used some of your user.css code to fix it and now officially the premium section tab isn't appearing and the context menu thingy also should mention that but it is fine it is gone now.
