### ISSUE TITLE
Error while updating theme

### ISSUE THREAD

**Issue by francescoaracu** [Daksh777/SpotifyNoPremium#44]
Using `update.bat` to update theme throws this error on W11:
![image](https://user-images.githubusercontent.com/48188510/154458237-6df42eb4-0673-4139-9d4f-57f3ee0c4130.png)

I'm using latest Spicetify and Spotify versions.

**Comment by Daksh777** [comment]
I've updated the script, please redownload and run it from here: https://raw.githack.com/Daksh777/SpotifyNoPremium/main/update.bat
