### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by 9dl** [Daksh777/SpotifyNoPremium#45]
How i can remove it?

**Comment by Daksh777** [comment]
What do you mean? Do you need help with installing this theme?

**Comment by 9dl** [comment]
Nono i accidentally started before installing spotify now i cant install spotify and my question is how i can remove it to install spotify and do the steps

**Comment by Daksh777** [comment]
That's alright, you can install Spotify and re-run the install.bat file and it will replace the downloaded files.

**Comment by 9dl** [comment]
Nope its giving everytime i start spotify installer a error

**Comment by Daksh777** [comment]
What error does it give?

**Comment by 9dl** [comment]
Transelated: Spotify could not be installed because the necessary files could not be created

![SpotifySetup_(3)_yRRMih0pPI](https://user-images.githubusercontent.com/80607793/155533311-19981de5-f313-432b-9bd8-ebdeda8a4c0a.png)

**Comment by Daksh777** [comment]
Please make sure there are no Spotify files anywhere.
Go to `C:\Users\YourUsernameHere\AppData\Local` and delete the Spotify folder and do the same for `C:\Users\YourUsernameHere\AppData\Roaming`

**Comment by 9dl** [comment]
I installed  it now but still the ads

**Comment by 9dl** [comment]
![Spotify_koLWLXi0vo](https://user-images.githubusercontent.com/80607793/155536053-89ec5407-e64d-45a5-b4ed-929ef096781a.png)

**Comment by Daksh777** [comment]
You need to run `install.bat` again.

**Comment by 9dl** [comment]
i did bro

**Comment by 9dl** [comment]
its still the same its not getting removed

**Comment by Daksh777** [comment]
Download search everything from https://www.voidtools.com/
In the app, search for Spotify and delete all folders which it shows

**Comment by 9dl** [comment]
Still i see Upgrade button

**Comment by Daksh777** [comment]
Can you confirm your Spotify version?

**Comment by 9dl** [comment]
![Spotify_1OKfpQOSNR](https://user-images.githubusercontent.com/80607793/155793818-7c2c0dc0-8b16-49fe-811c-849e1c948e7f.png)

**Comment by Daksh777** [comment]
Could you please try reinstalling Spotify and running the `install.bat` file again?
If that doesn't work, please contact me via Telegram (https://telegram.me/Daksh777) or Discord (Lars24#9047) so I can help you out further.

**Comment by Daksh777** [comment]
> i added you but you dont accept my fa

Please tell me your Discord ID, I'll send you a request.

**Comment by 9dl** [comment]
Vestige#0002 | 846618137571098644
