### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by StrikerOnLine** [Daksh777/SpotifyNoPremium#46]
When installing or updating spotify, the screen goes black.

**Comment by Daksh777** [comment]
Please run the `update.bat` script. The Spicetify CLI was updated today and it should now support the newest version of Spotify.

**Comment by Shituation** [comment]
Nope... still doesn't work... I tried it just right now...

![image](https://user-images.githubusercontent.com/43975882/156863432-461c5061-ebaf-4e58-a915-46c0ecaef983.png)

**Comment by Daksh777** [comment]
Can you confirm your Spotify and Spicetfy version to me?

**Comment by Shituation** [comment]
![image](https://user-images.githubusercontent.com/43975882/156886967-f2586c3b-2212-4697-9fe9-c424aa221780.png)

![image](https://user-images.githubusercontent.com/43975882/156887037-5379f885-5955-4572-a537-5ac7a8f1001b.png)

**Comment by Daksh777** [comment]
It seems like a problem with Spicetify itself.
Please downgrade to the older version as of now and block the updates.
I'll keep you updated when the problem gets fixed: https://github.com/spicetify/spicetify-cli/issues/1514

**Comment by Shituation** [comment]
can you point me to where to get an older version? (googled but got many fishy sites)
Also how do I block it from trying to update? (I imagine that blocking spotify with the firewall would prevent the app from working at all)

**Comment by Daksh777** [comment]
Hey @Shituation 
Can you try doing the following to check if Spicetify works on the latest version since it seems to be working for me:
- Reinstall Spotify
- Enter `spicetify backup apply`
- Run this PowerShell script: https://raw.githack.com/Daksh777/BlockTheSpot/master/SpotifyNoPremium.ps1

**Comment by vctr11** [comment]
i have the same problem, i have a black screen and tried reinstalling spotify. please fix this problem!

**Comment by MonkNo1** [comment]
> When installing or updating spotify, the screen goes black.

Ya Its Not Working Me To It was just comming as Black Screen 
![image](https://user-images.githubusercontent.com/61575072/156920485-e4e194ed-3760-41a7-b0e2-3375814c4800.png)

**Comment by MonkNo1** [comment]
> Thanks Buddy This Method Works And Now the Problem was Fixed 
![image](https://user-images.githubusercontent.com/61575072/156920679-24f21394-23c1-4aa5-8456-1b62f8d4683a.png)

**Comment by Daksh777** [comment]
Hi everyone, here are the steps to go back to an older version of Spotify and use this theme if Spotify shows blank for you:

1. Delete the `C:\Users\YourUsernameHere` and delete the `.spicetify` folder (should be present if you're an old Spicetify user)
2. Delete the `C:\Users\YourUsernameHere` and delete the `spicetify-cli` folder
3. Run this in PowerShell: (to fix environment variables if you're an old Spicetify user)
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1" | Invoke-Expression
```
4. Download `spicetify-2.9.1-windows-x64.zip` from [here](https://github.com/spicetify/spicetify-cli/releases/download/v2.9.1/spicetify-2.9.1-windows-x64.zip)
5. Extract and replace all the contents in `C:\Users\YourUsernameHere\spicetify-cli`
6. Download and install this old Spotify version `1.1.79.763.gc2965cdf`: https://drive.google.com/file/d/1xSCLG7tXcwwbogVwptCdROFxApC3wnOJ/view?usp=sharing
7. Run `spicetify backup apply`
8. Run this PowerShell script: https://raw.githack.com/Daksh777/BlockTheSpot/master/SpotifyNoPremium.ps1
9. Block updates by enter the following lines in CMD (***open as admin***):
```cmd
rm %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R
```

**Comment by Daksh777** [comment]
Hi everyone, here are the steps to go back to an older version of Spotify and use this theme if Spotify shows blank for you:

1. Delete the `C:\Users\YourUsernameHere` and delete the `.spicetify` folder (should be present if you're an old Spicetify user)
2. Delete the `C:\Users\YourUsernameHere` and delete the `spicetify-cli` folder
3. Run this in PowerShell: (to fix environment variables if you're an old Spicetify user)
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1" | Invoke-Expression
```
4. Download `spicetify-2.9.1-windows-x64.zip` from [here](https://github.com/spicetify/spicetify-cli/releases/download/v2.9.1/spicetify-2.9.1-windows-x64.zip)
5. Extract and replace all the contents in `C:\Users\YourUsernameHere\spicetify-cli`
6. Download and install this old Spotify version `1.1.79.763.gc2965cdf`: https://drive.google.com/file/d/1xSCLG7tXcwwbogVwptCdROFxApC3wnOJ/view?usp=sharing
7. Download and copy the `SpotifyNoPremium` folder in `C:\Users\YourUsernameHere\spicetify-cli\Themes`: https://github.com/Daksh777/SpotifyNoPremium/archive/main.zip
8. Run `spicetify config current_theme SpotifyNoPremium`
9. Run `spicetify backup apply`
10. Run this PowerShell script: https://raw.githack.com/Daksh777/BlockTheSpot/master/SpotifyNoPremium.ps1 (Right click > Run with Powershell)
11. Block updates by enter the following lines in CMD (***open as admin***):
```cmd
rm %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R
```

**Comment by Daksh777** [comment]
Hi everyone, here are the steps to go back to an older version of Spotify and use this theme if Spotify shows blank for you:

1. Go to `C:\Users\YourUsernameHere` and delete the `.spicetify` folder (should be present if you're an old Spicetify user)
2. Go to `C:\Users\YourUsernameHere` and delete the `spicetify-cli` folder
3. Run the `install.bat` script: https://raw.githack.com/Daksh777/SpotifyNoPremium/main/install.bat

**Comment by vctr11** [comment]
great work dude! thank you!!!!

**Comment by Shituation** [comment]
Thanks @Daksh777 ! seems to be working now. 
This is the output if it helps.
![image](https://user-images.githubusercontent.com/43975882/156925747-16c95d0b-908c-4f95-8f26-c936d01c163c.png)

**Comment by Daksh777** [comment]
@Shituation It seems like you didn't press yes for Spicetify, since we're deleting the Spicetify folders, Spicetify also gets removed. The theme wouldn't get applied if Spicetify isn't installed.

**Comment by Shituation** [comment]
> @Shituation It seems like you didn't press yes for Spicetify, since we're deleting the Spicetify folders, Spicetify also gets removed. The theme wouldn't get applied if Spicetify isn't installed.

Oops you are right... it was the habit when updating, sorry. Now it has given a clean output.
Thanks again!

**Comment by Daksh777** [comment]
We've switched to a cross-platform ad block so we no longer need to use BlockTheSpot, please make sure to use the latest update.bat and install.bat to get the latest features.

**Comment by Shituation** [comment]
Thanks!

**Comment by Shituation** [comment]
Daksh, I 've run the uptdate.bat and install.bat. Both asks me to install blockthespot. Is this normal?
Screenshot of latest install.bat from main page.
![imagen](https://user-images.githubusercontent.com/43975882/157864431-a5540f52-0643-490b-b42a-b5d2b84a40cf.png)

**Comment by Daksh777** [comment]
Please run the latest install.bat from here and that should work: https://raw.githack.com/Daksh777/SpotifyNoPremium/main/install.bat

You may now press No for Spicetify and it should still work

**Comment by Shituation** [comment]
Is this normal? (btw it seems to be working)
![imagen](https://user-images.githubusercontent.com/43975882/157865327-519b471d-846f-439c-a378-61bb346e81b6.png)

**Comment by Daksh777** [comment]
I did a bit of a mistake with the script, I'm going to fix it real quick, hold on.

**Comment by Daksh777** [comment]
Can you try now @Shituation?

**Comment by Shituation** [comment]
All seems good! thanks!
![imagen](https://user-images.githubusercontent.com/43975882/157869530-aec8c0b4-ac2c-4c02-8a2a-d75dbb214a4d.png)

**Comment by Andju1** [comment]
Help! The code says this.
![imagen_2022-03-12_145623](https://user-images.githubusercontent.com/101479516/158034702-6b2154d6-2d28-4fc8-86fc-92f3265ec201.png)

**Comment by Shituation** [comment]
Follow Daksh's guide up there:

1. Go to C:\Users\YourUsernameHere and delete the .spicetify folder (should be present if you're an old Spicetify user)
2. Go to C:\Users\YourUsernameHere and delete the spicetify-cli folder
3. Reinstall Spotify

Then
Use this script:
 https://raw.githack.com/Daksh777/SpotifyNoPremium/main/install.bat

**Comment by Andju1** [comment]
> Follow Daksh's guide up there:
> 
> 1. Go to C:\Users\YourUsernameHere and delete the .spicetify folder (should be present if you're an old Spicetify user)
> 2. Go to C:\Users\YourUsernameHere and delete the spicetify-cli folder
> 3. Reinstall Spotify
> 
> Then Use this script: https://raw.githack.com/Daksh777/SpotifyNoPremium/main/install.bat
The same problem, I already clicked yes and no and do the same process. The premium button didn't disappear and keep seeing ads.
![image](https://user-images.githubusercontent.com/101479516/158034918-3332b862-7296-4249-8108-8b83723de123.png)

**Comment by Shituation** [comment]
Mmmm... try to run it as admin (even if your user is admin). Also try to disable UAC if you have it enabled:
![image](https://user-images.githubusercontent.com/43975882/158035324-28ff5627-ccd0-45fb-9449-eb25b99fccc1.png)
![image](https://user-images.githubusercontent.com/43975882/158035336-9aa9332b-b910-4ad3-bc9b-0c8e702e0dc7.png)

**Comment by Andju1** [comment]
Nop, nothing working yet

> Mmmm... try to run it as admin (even if your user is admin). Also try to disable UAC if you have it enabled: ![image](https://user-images.githubusercontent.com/43975882/158035324-28ff5627-ccd0-45fb-9449-eb25b99fccc1.png) ![image](https://user-images.githubusercontent.com/43975882/158035336-9aa9332b-b910-4ad3-bc9b-0c8e702e0dc7.png)
> 
> Looks like for some reason the "main.zip" is not being downloaded for you...

**Comment by Shituation** [comment]
I've just tried to install it again on my system and it works. 
Can you download the "main.zip" file? if you try manually?

Open powershell and paste this command: 

Invoke-WebRequest -Uri 'https://github.com/Daksh777/SpotifyNoPremium/archive/main.zip' -OutFile 'temp.zip'

A zip file called "temp.zip" should be downloaded to the root of your username folder.

**Comment by Andju1** [comment]
> I've just tried to install it again on my system and it works. Can you download the "main.zip" file? if you try manually?
> 
> Open **powershell** and paste this command:
> 
> Invoke-WebRequest -Uri 'https://github.com/Daksh777/SpotifyNoPremium/archive/main.zip' -OutFile 'temp.zip'
> 
> A zip file called "temp.zip" should be downloaded to the root of your username folder.
> 
> (this is troubleshooting, it won't fix anything yet)

mmm... I think it doesn't make anything

**Comment by Daksh777** [comment]
@Andju1 Can you confirm if `C:\Users\Daksh\.spicetify\Themes\SpotifyNoPremium` exists?

**Comment by Swadine** [comment]
1. Go to C:\Users\YourUsernameHere and delete the .spicetify folder (should be present if you're an old Spicetify user) : DONE
2. Go to C:\Users\YourUsernameHere and delete the spicetify-cli folder : DONE
3. Reinstall Spotify - Spotify desktop app doesn't open anymore whatever I do.  
And in the further steps I get the same error as @Andju1 even though 
`C:\Users\YOURNAME\.spicetify\Themes\SpotifyNoPremium` exists.

**Comment by Daksh777** [comment]
@Andju1 @Swadine There's a bit of a problem with the script, I'm going to push an update to fix it ASAP. Sorry for the inconvenience.

**Comment by Daksh777** [comment]
Can you please check now @Andju1 @Swadine?

**Comment by Swadine** [comment]
@Daksh777 Yep, it works now! 😋

**Comment by Andju1** [comment]
> Can you please check now @Andju1 @Swadine?

It works for me too. Thanks!

**Comment by SofiaNLoop** [comment]
> Hey @Shituation Can you try doing the following to check if Spicetify works on the latest version since it seems to be working for me:
> 
> * Reinstall Spotify
> * Enter `spicetify backup apply`
> * Run this PowerShell script: https://raw.githack.com/Daksh777/BlockTheSpot/master/SpotifyNoPremium.ps1

Doesn't work yet... pls help!

**Comment by Shituation** [comment]
> > Hey @Shituation Can you try doing the following to check if Spicetify works on the latest version since it seems to be working for me:
> > 
> > * Reinstall Spotify
> > * Enter `spicetify backup apply`
> > * Run this PowerShell script: https://raw.githack.com/Daksh777/BlockTheSpot/master/SpotifyNoPremium.ps1
> 
> Doesn't work yet... pls help!

Hi, it does work, I'm using it; what is the problem? black screen? if so, you have to uninstall that version of spotify and install an older version as described by Daksh:

For now, the solution is to downgrade to an older version and stop the updates.
Download the old version here: https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.84.716.gc5f8b819-8.exe

To stop the updates, you have to create a folder named "Updates" inside %localappdata%\spotify and remove all permissions of all user groups on that folder.

**Comment by SofiaNLoop** [comment]
I don't understand haha

**Comment by SofiaNLoop** [comment]
where can I create the folder "updates"?

**Comment by SofiaNLoop** [comment]
here? 
![image](https://user-images.githubusercontent.com/76735847/169166178-f6ff3fb6-fa8d-458c-b49a-7c0d342a1cb3.png)

**Comment by Shituation** [comment]
> where can I create the folder "updates"?

C:\Users\YOUR.USERNAME.HERE\AppData\Local\Spotify

**Comment by Daksh777** [comment]
Thank you for helping them @Shituation 
If you still need help @SofiaNLoop, please see https://github.com/Daksh777/SpotifyNoPremium/issues/73#issuecomment-1126847432

**Comment by BogdanSasaki** [comment]
![image](https://user-images.githubusercontent.com/52134333/170726218-bc0fdf02-0c34-453f-ba5b-657ff3c09a25.png)
U gave a problem, I can't run it because my microsoft store is not compatible or version of them. What should I do?

**Comment by Shituation** [comment]
> ![image](https://user-images.githubusercontent.com/52134333/170726218-bc0fdf02-0c34-453f-ba5b-657ff3c09a25.png) U gave a problem, I can't run it because my microsoft store is not compatible or version of them. What should I do?

You must delete the store version first and install the desktop version. 
Download: https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.84.716.gc5f8b819-8.exe

**Comment by SofiaNLoop** [comment]
> Thank you for helping them @Shituation If you still need help @SofiaNLoop, please see [#73 (comment)](https://github.com/Daksh777/SpotifyNoPremium/issues/73#issuecomment-1126847432)

Thank u very much! @Shituation and @Daksh777  Now it works!

**Comment by MONKE121** [comment]
![image](https://github.com/Daksh777/SpotifyNoPremium/assets/112748093/389c2b3b-5e94-4f15-a765-515b88554831)


HELP PLEASE

**Comment by Shituation** [comment]
> ![image](https://user-images.githubusercontent.com/112748093/256826499-389c2b3b-5e94-4f15-a765-515b88554831.png)
> 
> HELP PLEASE

https://github.com/amd64fox/SpotX

**Comment by OliverJTX** [comment]
Hi there, @Shituation and @Daksh777! First of all, I wanted to tell you how much I love what you've done with the .bat and PowerShell scripts. I've learned a lot from you. I wanted to mention that I'm encountering the following issue, which seems to be related to permissions. After following the installation manual steps, I'm unable to proceed due to this. Thanks a bunch for your support! :D

![script_capture](https://github.com/Daksh777/SpotifyNoPremium/assets/74628620/ff8d759b-1e5b-414e-83f9-53bbf7986e5f)

**Comment by Daksh777** [comment]
Hey @OliverJTX, thank you so much!
Could you please create a new issue for this? Also, please post the error screenshot in English so I'll be able to see what the issue is.
