### ISSUE TITLE
Combine with Adblock Spicetify extension instead of BlockTheSpot

### ISSUE THREAD

**Issue by itsmeboy0** [Daksh777/SpotifyNoPremium#49]
The [Adblock](https://github.com/CharlieS1103/spicetify-extensions/tree/main/adblock) extension is excellent, and it seems to be better as it is a spicetify extension. Thus, I won't need to reapply BlockTheSpot after applying spicetify changes. Also, since there is no batch or script file involved, there is no worry about Defender flagging it.

**Comment by Daksh777** [comment]
I'm going to have a look at it, thank you for the suggestion.

**Comment by itsmeboy0** [comment]
The best option would be to include [`adblock.js`](https://github.com/CharlieS1103/spicetify-extensions/blob/main/adblock/adblock.js) to this repo and it would be just under one install in the Spicetify Marketplace.

**Comment by Daksh777** [comment]
That extension works quite well, this makes everything super convenient and cross-platform!
Thank you so much for the suggestion!
