### ISSUE TITLE
Discovery on the Spicetify Marketplace

### ISSUE THREAD

**Issue by itsmeboy0** [Daksh777/SpotifyNoPremium#50]
I would love to see this theme in the [Spicetify Marketplace](https://github.com/spicetify/spicetify-marketplace). Here are the things that you need to do:

> ## Getting your extension/theme on Marketplace
> In order to show up in the custom app, you'll need to make a public GitHub repo that meets these requirements:
> * Have the matching **GitHub topic tag** ("spicetify-extensions" or "**spicetify-themes**")
> * Have a valid **`manifest.json`** in the root folder (format outlined below)

> ### Theme manifests
> * `name`: Your theme name
> * `description`: Description for your theme
> * `preview`: A path to your preview image. Must be relative to your project root. 
> * `usercss`: A path to your user.css file. Must be relative to your project root. 
> * `schemes`: A path to your color.ini file. Must be relative to your project root. 
> * `readme`: The filename for your extension's README file. Must be relative to your project root. 
> * `branch`: Optional branch to specify. Will use default branch if none. 
> * `authors`: Optional array of authors with names and urls. Will use repo owner if none. 
> 
> e.g. 
> ```json
> {
>     "name": "Theme Name",
>     "description": "Theme description",
>     "preview": "filepathFromGitRepo/theme.png",
>     "readme": "README.md",
>     "usercss": "filepathFromGitRepo/user.css",
>     "schemes": "filepathFromGitRepo/color.ini",
>     "branch": "beta-release",
>     "authors": [
>         { "name": "theRealPadster", "url": "https://github.com/theRealPadster" },
>         { "name": "CharlieS1103", "url": "https://github.com/CharlieS1103" }
>     ]
> }
> ```

See an example here: https://github.com/williamckha/spicetify-fluent

**Comment by Daksh777** [comment]
Sounds great, will do that today @itsmeboy0.
