### ISSUE TITLE
Adblock not fully worked

### ISSUE THREAD

**Issue by Pein1911** [Daksh777/SpotifyNoPremium#53]
I still see ad sometime, may be need a update . Spotify v1.1.80.699

**Comment by Daksh777** [comment]
Which ad are you talking about? (Banner ads, popup ads, audio ads)

**Comment by Pein1911** [comment]
> Which ad are you talking about? (Banner ads, popup ads, audio ads)

It was audio ads after update, I just un- then reinstalled and test for couple days and it has fixed for now, thank you again :D
