### ISSUE TITLE
can't render UI

### ISSUE THREAD

**Issue by WDF3508** [Daksh777/SpotifyNoPremium#56]

**Comment by WDF3508** [comment]
![Uploading Screenshot 2022-03-18 211541.png…]()

**Comment by WDF3508** [comment]
Before the last updates, all worked fine

**Comment by Stevealv121** [comment]
I can't neither, what did you do?

**Comment by WDF3508** [comment]
> 

I'v simply reinstalled the whole spotify, spicetify and other addons. Also I found that my theme (dribbish dynamic) caused this.
