### ISSUE TITLE
unable to reinstall using install.bat

### ISSUE THREAD

**Issue by VelamyGH** [Daksh777/SpotifyNoPremium#57]
at first it had come up with unverified developer but i ran it anyways, only to find it say this: 
![image](https://user-images.githubusercontent.com/48131627/159130449-222a48f1-d1df-44eb-aac5-9447fc4c25a5.png)
and then i had ran with administrator which gave better results but still cannot find powershell
![image](https://user-images.githubusercontent.com/48131627/159130491-0b5eb6e0-f3eb-42be-a809-f1596aae91fe.png))

Spotify for Windows
1.1.81.604.gccacfc8c

**Comment by Daksh777** [comment]
What Windows version are you on?

**Comment by VelamyGH** [comment]
Edition	Windows 10 Home
Version	21H2
Installed on	‎7/‎5/‎2020
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by Daksh777** [comment]
Can you make sure if Powershell is installed on your system?

**Comment by VelamyGH** [comment]
yes its installed, im pretty sure something messed up with environment tables but im now encountering a problem where the upgrade button is still there and it does not ask for git being installed or to install blockthespot

**Comment by Daksh777** [comment]
Seems like you're using an old `install.bat` script, make sure to get the latest one from the README of this repo.
Regarding the environment variables, make sure that you have Powershell in the system PATH
![image](https://user-images.githubusercontent.com/43648146/159148202-a8f671fb-8790-4f25-8b2c-9fd8fa0f4b9c.png)

**Comment by VelamyGH** [comment]
fixing the environment tables seems to work if i run the .bat as admin, ads seem to be gone? however upgrade button still remains and i am not asked for any blockthespot after running install
![image](https://user-images.githubusercontent.com/48131627/159148282-eec3b212-30a3-439d-b990-601121193d7f.png)
![image](https://user-images.githubusercontent.com/48131627/159148285-3abf3125-67be-4bcf-8ec4-dcb9c82d9092.png)

**Comment by Daksh777** [comment]
Yes, we've switched to a cross-platform ad-block solution so we're no longer BlockTheSpot.
About the upgrade button, can you tell me your Spotify version?

**Comment by VelamyGH** [comment]
ah wow, good job on the built in solution :) 
as for my version it is windows 1.1.81.604.gccacfc8c , as stated in my original comment

**Comment by Daksh777** [comment]
Is it possible for you to connect over Discord or Telegram? I'll need to have a look at your Spotify client and you'll have to use the developer tools to help me find a fix for the upgrade button because I do not see them on my Spotify client on the same version.
My Telegram: https://telegram.me/Daksh777
My Discord: Lars24#9047

**Comment by VelamyGH** [comment]
well its pretty ridiculous how sometimes the simplest solutions often work lol, just restarted my pc and the button is gone. my apologies for the inconviniences and for all my problems being user specific but youve been a great help :) will update with anything i find in the future

**Comment by Daksh777** [comment]
No worries! Glad that I could help.
