### ISSUE TITLE
can't render UI

### ISSUE THREAD

**Issue by Stevealv121** [Daksh777/SpotifyNoPremium#58]
![image](https://user-images.githubusercontent.com/33636552/159140500-21ce8e71-c340-4062-9e6b-27c854eef9f8.png)

Since the last update, it does not render the UI.

**Comment by Stevealv121** [comment]
After reinstalling spotify and spicetify, still broken.
spicetify settings
![image](https://user-images.githubusercontent.com/33636552/159141010-777a4bc9-6e94-4690-a3c2-415da1656ae9.png)

**Comment by Daksh777** [comment]
Can you tell your Spotify version?
Also, does this not help: https://github.com/Daksh777/SpotifyNoPremium/issues/46#issuecomment-1059945231

**Comment by Stevealv121** [comment]
https://github.com/Daksh777/SpotifyNoPremium/issues/46#issuecomment-1059945231 it worked!
Thanks man! Great work!
