### ISSUE TITLE
error Theme "SpotifyNoPremium" not found

### ISSUE THREAD

**Issue by AnshulAgarwal08** [Daksh777/SpotifyNoPremium#61]
On a MacOs 12.3

**Comment by Daksh777** [comment]
Can you please connect with me over Discord or Telegram?
I'll need to have a look at a few things since I don't have MacOS to test it out myself.

My Telegram: https://telegram.me/Daksh777
My Discord: Lars24#9047

**Comment by Daksh777** [comment]
Issue resolved.
Mac users may need to run `xcode-select --install` before running the `git clone` command for it to work.
