### ISSUE TITLE
The spotify songs repeats the first second many times

### ISSUE THREAD

**Issue by sebastiansierrat** [Daksh777/SpotifyNoPremium#62]
I have this problem recently with the latest version of spotify, when I play a song, the first second is played and then that second is repeated about 5 times or sometimes more times, what can it be?, I already tried uninstalling everything and reinstalling but the problem continues.

**Comment by Daksh777** [comment]
This is a big with Spotify itself.
You'll have to wait for Spotify to give an update with the fix.
More info here: https://community.spotify.com/t5/Desktop-Windows/Starting-a-song-short-loop-in-the-beginning-windows-desktop/td-p/5356090
