### ISSUE TITLE
Banner ads visible.

### ISSUE THREAD

**Issue by fosam** [Daksh777/SpotifyNoPremium#63]
Hello Daksh, How are you? :)

I'm using Spotify for Windows 1.1.81.604.gccacfc8c, but the banner ads are not getting hidden.

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/162584320-aac2ef0c-7c78-44cf-9936-61777040738d.png>
</details>

Is this class not included in `user.css`?

**Comment by Daksh777** [comment]
Can you confirm if you're talking about the popup ads or the banner ad above the music control buttons?

**Comment by fosam** [comment]
The banner ad above the music control buttons.

**Comment by Daksh777** [comment]
I don't see them on my Spotify client, could you try enabling devtools and using inspect element to get the class/id of the ad?
Here's how to enable devtools: https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063

**Comment by fosam** [comment]
It's not so simple using the dev tools, any way to enable the inspect element right click?

**Comment by Daksh777** [comment]
Unfortunately, it's not possible to use the right-click method as of now. You have to follow this:

- Close Spotify if it's running
- Add `--remote-debugging-port=9222` flag to Spotify shortcut
- Open Spotify
- Open Chrome (normal web browser)
- Go to `chrome://inspect/`
- List of remote targets should appear with `Spotify - Web Player` entry
- Click inspect
![image](https://user-images.githubusercontent.com/43648146/162699397-f53b5cd5-f3af-4184-b737-ecf0a8a330bd.png)

**Comment by fosam** [comment]
Yes, i've done it, but how can i find the banner in the dev tool? with the right click to inspect it went directly to the element, now it seems that i have to look for it?

**Comment by Daksh777** [comment]
Oh, you have to click this icon to use your mouse to select the ad div
![image](https://user-images.githubusercontent.com/43648146/162715532-4a9b89bf-0609-4a25-8532-3f6c96bb346b.png)

When you enable that and click on the ad, it will select the element for you.

**Comment by fosam** [comment]
Daksh, Thank you for your support, now i will post the result when i'm on my PC.

**Comment by fosam** [comment]
<details>
<summary>Class</summary>
<img src=https://user-images.githubusercontent.com/52612348/163396504-a4ec0f7b-1807-4684-aeec-3d4718ad76b5.png>
</details>

**Comment by fosam** [comment]
OH! i think that is my mistake.

In my user.css file, i have only from lines `167 -> 213` as i'm only using Spotify `1.1.74+`

I'm not sure why that class is not in the lines i mentioned above?

It's not a big deal though, i can certainly just include it somewhere between `167 -> 213`

**Comment by Daksh777** [comment]
If you did not modify anything in the `user.css` file, that shouldn't have happened and all the lines in the `user.css` should've been copied. Are you sure you didn't modify the file?

**Comment by fosam** [comment]
Oh sorry, maybe i didn't explain well enough 😁

I mean i'm intentionally using `167 -> 213` as i don't use any older version of Spotify.

**Comment by Daksh777** [comment]
Ah, that makes sense.
I advise you to use the entire file (it will barely affect performance) and sometimes a mix of both older and newer lines is needed for it to block the ads.

**Comment by Daksh777** [comment]
It uses a generic modal which is being used for other modals like the delete playlist modal so I can't really hide/remove that. I'm looking for another way which will remove this.
