### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by JotaroKujo0525** [Daksh777/SpotifyNoPremium#65]
Doing the manual insrallation but i can't understand this error when doing `spicetify config current_theme SpotifyNoPremium`
![image](https://user-images.githubusercontent.com/77835007/164168508-5db88a14-9b23-4634-973f-026c2accb28f.png)

**Comment by Daksh777** [comment]
You have to go to `C:\Users\YOURUSERNAME\.spicetify` and edit the `config-xpui.ini` file and add the following line here: `C:\Users\Daksh\YOURUSERNAME\Roaming\Spotify\prefs`
![image](https://user-images.githubusercontent.com/43648146/164233234-ab881a38-8779-483a-bfbb-f7aa457da4fb.png)

Also, make sure your Spotify is not from Microsoft Store but from https://www.spotify.com/us/download/windows/

**Comment by JotaroKujo0525** [comment]
Oh uh slr, but i already found this out by going into the spicetify repository, but still thanks for the response!
