### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by DemonicHelper** [Daksh777/SpotifyNoPremium#66]
I've been trying to install the "crack" and I can't do so, this message shows up when i try click "no" when it asks me if i have spicetify CLI installed
![pito](https://user-images.githubusercontent.com/104119415/164371411-fdbedff7-7813-4c9c-ad6d-9474fed76349.png)

**Comment by artemcodes** [comment]
```bash
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1" | Invoke-Expression
```
Enter

**Comment by Daksh777** [comment]
Can you please provide an English translation for this @DemonicHelper?

No, that's not an issue related to Spicetify since it installed correctly @artemcodes

**Comment by DemonicHelper** [comment]
> ```shell
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1" | Invoke-Expression
> ```
> 
> Type in powershell

Didn't work

**Comment by DemonicHelper** [comment]
> Can you please provide an English translation for this @DemonicHelper?
> 
> No, that's not an issue related to Spicetify since it installed correctly @artemcodes

It says cannot find a part of the path

**Comment by Daksh777** [comment]
Can you confirm if the `.spicetify` folder is present in `C:\Users\YOURNAME\.spicetify`?

**Comment by DemonicHelper** [comment]
> Can you confirm if the `.spicetify` folder is present in `C:\Users\YOURNAME\.spicetify`?

Yes, It is in there
![pito 12](https://user-images.githubusercontent.com/104119415/164910718-a124a930-cc1c-46ff-83a7-30186aca313c.png)

**Comment by Daksh777** [comment]
Okay, can you make sure if a directory named `SpotifyNoPremium` exists in the `.spicetify/Themes` folder?

**Comment by DemonicHelper** [comment]
> Okay, can you make sure if a directory named `SpotifyNoPremium` exists in the `.spicetify/Themes` folder?

No, there isnt, Do i have to put it in it?

**Comment by Daksh777** [comment]
Really sorry for the late reply, could you please switch your computer's language to English so I can properly debug the error and send the screenshot/log?

**Comment by DemonicHelper** [comment]
> Really sorry for the late reply, could you please switch your computer's language to English so I can properly debug the error and send the screenshot/log?

Ok, what do i send you?

**Comment by Daksh777** [comment]
Just run the script and send the screenshot of the error with your computer language in English

**Comment by DemonicHelper** [comment]
![image](https://user-images.githubusercontent.com/104119415/166085546-51fa60c4-adf1-4e4e-845b-45b17a47a80c.png)
This is what it says

**Comment by STAGhost12** [comment]
waiting for the solution :(

**Comment by Daksh777** [comment]
Sorry for the delay, I'm looking into the problem and I'll try to fix this. I'll keep you updated.

**Comment by Daksh777** [comment]
Please run the updated `install.bat` script and it should work now.
