### ISSUE TITLE
stopped working all of a sudden

### ISSUE THREAD

**Issue by Zaidzyy** [Daksh777/SpotifyNoPremium#67]
hey bro this is not working anymore , it was working earlier tho and it suddenly stopped working and showed black screen and i tried your fix for that and the black screen went but i didnt get spotify premium features as it is said in ur readme. pls try to help me fix it

**Comment by Daksh777** [comment]
Do you still require help or is it resolved @Zaidzyy?

**Comment by Zaidzyy** [comment]
it got resolved and it started working again thx!
