### ISSUE TITLE
Blank screen on Spotify. (Linux)

### ISSUE THREAD

**Issue by fuhiragi** [Daksh777/SpotifyNoPremium#68]
Hi. I'm trying to install the theme via manual method but when I apply the theme along with adblock extension, it appeared as a blank screen. (I know that there is a fix but it's for Windows only. I use Linux.)

- Arch Linux, Spotify and Spicetify installed via AUR, up to date.

**Comment by Daksh777** [comment]
Can you tell me your spicetify version?
Run `spicetify -v` to get it.

**Comment by Daksh777** [comment]
Can you try reinstalling Spicetify?

**Comment by fuhiragi** [comment]
I reinstalled Spicetify. Issue still presents, somehow.

**Comment by Daksh777** [comment]
Well this is weird, could you try deleting all spicetify related directories and installing using shell:
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh`

**Comment by fuhiragi** [comment]
The shell version didn't fix it either. Strange.

**Comment by Daksh777** [comment]
Can you tell what's your Spotify version?

**Comment by fuhiragi** [comment]
Well, just exactly like what AUR gives to me at the moment.
![image](https://user-images.githubusercontent.com/102655447/165883634-172fc02a-ed77-4ace-a161-98b820dfaec2.png)

**Comment by Daksh777** [comment]
I will check on an Arch VM if it works for me, in the meanwhile, can you try using some other theme other than this and see if that helps?

**Comment by erdemozdemir98** [comment]
Same issue here. I tried removing the .spicetify folder from /home and running manual instructions again but it didn't work. I'm using the latest version from AUR. I tried installing Comfy theme but the result was same, only background color was changed. So I guess new Spotify update broke something again.

**Comment by Daksh777** [comment]
Okay, I just went through the issues on the main repo and this solution might work, please try this:
Remove the `Backup` folder in the `.spicetify` folder, then reinstall Spotify and run`spicetify backup apply` 

Please let me know if it works.

**Comment by erdemozdemir98** [comment]
There wasn't a Backup folder in .spicetify, I tried it without removing the folder and it did not work.

**Comment by erdemozdemir98** [comment]
Well, it didn't work because versions of the spotify-snapstore, spotify-edge and spotify packages from AUR are all same and I guess they're all up-to-date. I still tried with all 3 packages but no luck.

**Comment by Daksh777** [comment]
Oh, I thought you were on the same version as @fuhiragi. I can't seem to find any other solution for this.
Could you please open an issue in the main repo since this issue isn't directly related to this theme? Create an issue here: https://github.com/spicetify/spicetify-cli/issues/new?assignees=&labels=%F0%9F%90%9B+bug&template=bug_report.yml

**Comment by erdemozdemir98** [comment]
There was an already existing issue for that on spicetify repo, so I commented on it. I guess that is a Linux-specific issue because my friends on Windows can use it without any problems. Thanks for your help and your awesome theme by the way, I'm really enjoying it.

**Comment by Daksh777** [comment]
Thank you so much! :D 
I'll close this issue for now, do let me know what solution is so I can add it to the readme.
