### ISSUE TITLE
Spotify screen stays black

### ISSUE THREAD

**Issue by valecer2411** [Daksh777/SpotifyNoPremium#70]
Hi, I just installed with the "install" file with no error shown in the cmd and when it opens Spotify the screen stays black.
I tried reinstalling spotify and doing it again but nothing happens. Im using the lastest version of Spotify and the lastest "install" file. Also, spicetify is updated.

**Comment by Daksh777** [comment]
Can you please check if this fixes the issue: https://github.com/Daksh777/SpotifyNoPremium/issues/46#issuecomment-1059945231

**Comment by valecer2411** [comment]
yes, it worked! Thanks
