### ISSUE TITLE
How to remove indent? (Linux)

### ISSUE THREAD

**Issue by voedev** [Daksh777/SpotifyNoPremium#71]
![image](https://user-images.githubusercontent.com/42519520/167413933-df65e7d5-a1ff-4364-ab28-4775d5714d69.png)

How to remove this indent for the lyric section?

Windows doesn't have this problem, but not Linux.

Spotify version: 1.1.84.716.gc5f8b819 [link](https://flathub.org/apps/details/com.spotify.Client)
Spicetify: 2.9.8

**Comment by Daksh777** [comment]
Can you confirm if this problem happens with different themes as well?

**Comment by voedev** [comment]
The problem persists on other themes.

**Comment by Daksh777** [comment]
Then it is a problem with Spotify itself, the problem used to exist on Windows too but was fixed after a Spotify update so you'll likely have to wait for an update.
