### ISSUE TITLE
Black/blank screen

### ISSUE THREAD

**Issue by Viserix** [Daksh777/SpotifyNoPremium#73]
Hi everyone, here are the steps to fix this problem, I've fixed the install script:

1. Go to `C:\Users\YourUsernameHere` and delete the `.spicetify` folder (should be present if you're an old Spicetify user)
2. Go to `C:\Users\YourUsernameHere` and delete the `spicetify-cli` folder
3. Reinstall Spotify
4. Run the `install.bat` script: https://raw.githack.com/Daksh777/SpotifyNoPremium/main/install.bat (*Press yes for Spicetify*)

_Originally posted by @Daksh777 in https://github.com/Daksh777/SpotifyNoPremium/issues/46#issuecomment-1059945231_

**Comment by Viserix** [comment]
i followed the steps and i get this and spotify screen goes black
![Captura de pantalla (2)](https://user-images.githubusercontent.com/102504827/168444928-f9d1fbe9-fbe3-469a-ad28-a1faf08029d1.png)

**Comment by Daksh777** [comment]
As I mentioned at the top of the README: 
Do not update to `1.1.85.895.g2a71e1b8`. Follow this issue for more info: https://github.com/spicetify/spicetify-cli/issues/1660

For now, the solution is to downgrade to an older version and stop the updates. 
Download the old version here: https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.84.716.gc5f8b819-8.exe

To stop the updates, open Admin Command Prompt and type these commands one by one:
`rm %localappdata%\Spotify\Update` (Change `rm` to `del` in Windows 7, or delete manually)
`mkdir %localappdata%\Spotify\Update`
`icacls %localappdata%\Spotify\Update /deny "%username%":D`
`icacls %localappdata%\Spotify\Update /deny "%username%":R`

**Comment by nvt194** [comment]
Hello, what about Mac os/Linux, I'm facing the same issue.

**Comment by Daksh777** [comment]
For Mac OS, you can download old Spotify from here: https://spotify.en.uptodown.com/mac/download/4685597
And then follow these to block the updates: https://youtu.be/lMDazdNJ1mo?t=93

**Comment by Daksh777** [comment]
The issue has been fixed, please update your Spotify and run `update.bat` or if you're on Linux/MacOS, run `spicetify upgrade` and `spicetify auto`
