### ISSUE TITLE
[ADS] Non blocked ad showing up from time to time.

### ISSUE THREAD

**Issue by Shituation** [Daksh777/SpotifyNoPremium#74]
Using the recommended version (older + no-updates) 1.1.46.716.
This ad seems to bypass the block:

![image](https://user-images.githubusercontent.com/43975882/168608718-fbd86f60-4b67-40ab-a3cd-4c1a84d90c11.png)

The rest is all OK, no music interruptions, can go forward and backwards without limits, etc..

**Comment by Shituation** [comment]
My bad version was 
![image](https://user-images.githubusercontent.com/43975882/168621791-2c04fcc6-7fe0-4458-ba7a-954eeb3b1da5.png)

Also, I see it says after reboot it will update, even when I made the update folder and blocked permissions.

**Comment by Daksh777** [comment]
Does the banner not get hidden automatically after a second or two?
About the update issue, can you delete all content in `%appdata%/Update` and then disable permissions for all user groups?

**Comment by Daksh777** [comment]
Okay, I will check it out and keep the issue open in the meanwhile

**Comment by SapitoSucio** [comment]
I do get some of those ads from time to time and as @Shituation says, they don't fade away after some time, you have you click the close button

**Comment by Daksh777** [comment]
Is the problem still relevant @SapitoSucio @Shituation?

**Comment by Shituation** [comment]
The ads show up and close now. I'm using Spotify for Windows
1.1.84.716.gc5f8b819 though. I would say its fixed.

**Comment by Daksh777** [comment]
Got it, thank you for confirming.
Also, maybe you should update to the latest version?

**Comment by Shituation** [comment]
> Got it, thank you for confirming. Also, maybe you should update to the latest version?

You mean spotify version? It works as it is for now... what convenient new features are implemented in the new version?  I'm starting to believe that updates on most software nowadays are all about ads or new ways to suck private info... I don't know.

**Comment by Daksh777** [comment]
Ahh, okay. That makes sense, no worries!
