### ISSUE TITLE
Upgrade to Premium is back after the last update

### ISSUE THREAD

**Issue by Dark-Yox** [Daksh777/SpotifyNoPremium#75]
Spotify version : 1.1.87.612
Spicetify version : 2.10.1

![image](https://user-images.githubusercontent.com/45209462/173020468-cc716148-f21a-4bce-9a18-9766fef58ed8.png)

**Comment by Daksh777** [comment]
It's hidden/removed in my Spotify client. Can you please try to enable dev tools (using `spicetify enable-devtools`) and send a screenshot of it (while you have selected the "Upgrade to Premium" element)?

**Comment by SaberAkiyama** [comment]
> Spotify version : 1.1.87.612 Spicetify version : 2.10.1
> 
> ![image](https://user-images.githubusercontent.com/45209462/173020468-cc716148-f21a-4bce-9a18-9766fef58ed8.png)

Same here I was inspection with DevTools. Screenshot below:
By the way, this is ```v1.1.87.612.gf8d110e2```
![Screenshot 2022-06-12 095721](https://user-images.githubusercontent.com/48464326/173211098-d4bac0d3-0747-4721-a4b9-96b22c665f48.png)

**Comment by Daksh777** [comment]
Are you sure you have not modified `user.css`? Because that class is already being hidden:
https://github.com/Daksh777/SpotifyNoPremium/blob/521109a5981566a288be2ee29266b3b231c0a471/user.css#L12-L15

**Comment by SaberAkiyama** [comment]
I don't think the ```user.css``` file didn't copy to Spotify app

**Comment by Daksh777** [comment]
Can you check in the sources tab?
![image](https://user-images.githubusercontent.com/43648146/173746032-6dfd1f4b-89e2-409e-84e0-d18898e611b1.png)

**Comment by IamNickerson** [comment]
Could be you have installed a second theme because i tried installing spotifynopremium and another theme in marketplace and it caused spotifynopremium theme not to work and another theme to work it could be bug or maybe you can only make one theme work in marketplace.

**Comment by Daksh777** [comment]
Yes, it's entirely possible for a second theme to be interfering with the CSS of my theme. What I'll do is add the `!important` property to the CSS rules and hopefully, that should override the second theme's CSS rules.

**Comment by IamNickerson** [comment]
> Yes, it's entirely possible for a second theme to be interfering with the CSS of my theme. What I'll do is add the `!important` property to the CSS rules and hopefully, that should override the second theme's CSS rules.

or easier option what i did is i copied the entire css code of spotifynopremium theme and pasted on the theme css which theme i am gonna use and it will remove the upgrade to Premium,bunch of ads and what it normally does.

**Comment by Dark-Yox** [comment]
I reinstalled the last version, it fixed the problem. Thank you !
