### ISSUE TITLE
Heur.BZC.ONG.Boxter.331.0652B23C

### ISSUE THREAD

**Issue by catb0x** [Daksh777/SpotifyNoPremium#76]
Bitdefender classifies the theme as a virus.. idk what to do
![image](https://user-images.githubusercontent.com/77354428/174430451-5a57829a-755d-4d84-b5d7-89198f6b197f.png)

**Comment by Daksh777** [comment]
Seems like this detection is a false positive and common with developers: https://www.reddit.com/r/BitDefender/comments/ljsjtt/false_positives_heurbzcpzqboxter811/

I'll submit this as a false positive to BitDefender and that should hopefully solve the problem.
However, to install the theme as of now, you can just disable BitDefender and run it and that should work.

**Comment by Daksh777** [comment]
Should be fixed in the upcoming updates of BitDefender
![image](https://user-images.githubusercontent.com/43648146/176086633-1dba1dcd-dc08-452a-9e5b-23435d73c6cd.png)
