### ISSUE TITLE
[Question] How to remove "Upgrade to Premium button"

### ISSUE THREAD

**Issue by fosam** [Daksh777/SpotifyNoPremium#8]
Hello Daksh

I'm looking for a way to get rid of `Upgrade to Premium` in the profile drop-down menu without using spicetify with a custom theme.

Do you happen to know which line in `xpui.css` to edit?

I don't know CSS, that is why i'm asking for your help here.

Windows 10, 1.1.62.583.gdac868ed-a

Thanks!

**Comment by Daksh777** [comment]
Hey @fosam 

I haven't checked `xpui.css` so that I can tell which line to edit, it's a very large file and it's difficult to find that element. However, if you already use a custom Spicetify theme, you can add this to the `user.css` file of your custom theme, and it will remove that item from the drop-down menu:

```
.upgrade-button, button[data-menu-item="upgrade-account"], .main-contextMenu-menuItem a[href="https://www.spotify.com/premium/"], button[id="upgradeAccount"] {
  display: none !important;
}
```

**Comment by fosam** [comment]
Thank you.

I will try it and let you know

**Comment by fosam** [comment]
I added your css code to a custom theme and it did the job.

However, i'm wondering which files do get replaced when we apply with Spicetify? does Spicetify copy the content of `user.css` and puts it in the default `xpui.css` of Spotify at `%userprofile%\AppData\Roaming\Spotify`?

**Comment by Daksh777** [comment]
You are correct. The `user.css` gets copied to `%AppData%\Roaming\Spotify\Apps\xpui`
![image](https://user-images.githubusercontent.com/43648146/124532343-f6c60800-de2d-11eb-81af-d654393510fd.png)

**Comment by fosam** [comment]
Thanks!

Though i wish there was a method to remove the `Upgrade to Premium` in the original `xpui.css` without needing Spicetify as this would be useful for users who don't use custom themes/Spicetify.

I tried to add your css code directly under the original `xpui.css` just to see if it would work, but unfortunately it did not.
but anyway this is much better than nothing.

**Comment by Daksh777** [comment]
I'm pretty sure there is a way to do it but it must be very tedious and it's just better to apply a theme after every update than going through multiple CSS files to change that one thing. The auto-install script makes it even easier.
