### ISSUE TITLE
Upgrade button is still in there

### ISSUE THREAD

**Issue by matheesha-pathirana** [Daksh777/SpotifyNoPremium#81]
**Successfully installed the program but upgrade button is still in there**

![image](https://user-images.githubusercontent.com/66365654/175881643-82881714-082e-4bc0-b1d3-b43a1813b36f.png)
**this is my spotify version**

![image](https://user-images.githubusercontent.com/66365654/175881919-1b5770fd-2ade-443f-b545-7d78b929c65b.png)

**Comment by Daksh777** [comment]
For some reason, I don't see the Upgrade button on my client. Can you please use devtools and send me the parent element of the upgrade button and I'll see what can be done? Here's how to enable devtools:

- add `--remote-debugging-port=9222` flag to Spotify shortcut
- restart Spotify 
- open chrome and go to `chrome://inspect/`
- list of remote targets should appear with Spotify - Web Player entry
- click inspect

**Comment by dibowz** [comment]
> For some reason, I don't see the Upgrade button on my client. Can you please use devtools and send me the parent element of the upgrade button and I'll see what can be done? Here's how to enable devtools:
> 
> * add `--remote-debugging-port=9222` flag to Spotify shortcut
> * restart Spotify
> * open chrome and go to `chrome://inspect/`
> * list of remote targets should appear with Spotify - Web Player entry
> * click inspect

Hi, I did the favor as per your guidance, here's the evidence:
![image](https://user-images.githubusercontent.com/32085882/176072320-a2f600a5-5b3c-413f-bc8c-e31ad084a0e8.png)

**Comment by Daksh777** [comment]
Can you try adding the following line in `user.css` (it should be located in `%userprofile%\.spicetify\Themes\SpotifyNoPremium`):

```css
.Button-y0gtbx-0[aria-label="Upgrade to Premium"] {
  display: none !important
}
```

**Comment by dibowz** [comment]
> Can you try adding the following line in `user.css` (it should be located in `%userprofile%\.spicetify\Themes\SpotifyNoPremium`):
> 
> ```css
> .Button-y0gtbx-0[aria-label="Upgrade to Premium"] {
>   display: none !important
> }
> ```
> 
> If that worked, I'll add it to the main CSS

I already added the line in the `user.css`, saved it, relaunch Spotify, but nothing works. Still have the upgrade button.
![image](https://user-images.githubusercontent.com/32085882/176108041-c0879068-aafc-42f2-99b8-c8c75ebc1799.png)

Also still have this in the inspect
```html
<button spec="[object Object]" class="Button-y0gtbx-0 jjUWAm Upqw01TOXETOmR5Td7Dj" title="Upgrade to Premium" aria-label="Upgrade to Premium">Upgrade</button>
```
