### ISSUE TITLE
Please for some help or at least some link pls

### ISSUE THREAD

**Issue by thecappadonna** [Daksh777/SpotifyNoPremium#82]
Can you help me? PLEASE...I spend my whole day but nothing... It's about goToSong.js extension for Spicetify...I receive the error and in the readme says to change the delay...But I've noticed that when I change the delay time in Spotify... but when I check the goToSong.js nothing changes there... The timer is still at 200ms...When I go to PowerShell and add Spicetify apply, everything is OK..but for goToSong.js says " error Extension " goToSong.js " not found  "... When I installed the extension it was working... well kind of...Sometimes I was receiving the same error...But it was working from time to time...Now cant make it work even once :( First, when I installed it, I did it from Spotify/Marketplace... when I was looking at how to fix it...I found the Extension in Github and put it in Extensions, but that didn't help :( Can't understand why I receive this error when I do Spicetify apply when goToSong.js is there...Why it's saying it can't be found? :( and why after I change the delay from Spotify, nothing changes in the .js file? I've tried to change the delay from the js file directly and do apply after that...But when I go to Spotify...The delay is not changed... Sorry for the spam, just wanted to explain everything. I really LOVE this Extension... I hate scrolling to the middle of the playlist for example where the song is playing... and I want to listen to some other song that is close to the one I'm listening atm... I just like it a lot and can't understand where is the problem...Please, guys... Is there someone who can help me? I beg u!!!

**Comment by Daksh777** [comment]
Hi @thecappadonna, this repo is not related to that extension but if you want help, you can DM me either on Discord (Lars24#9047) or Telegram (https://t.me/Daksh777) and I can try to help you out.

**Comment by thecappadonna** [comment]
> Hi @thecappadonna, this repo is not related to that extension but if you want help, you can DM me either on Discord (Lars24#9047) or Telegram (https://t.me/Daksh777) and I can try to help you out.

Bruh I really appreciate that you answer at least... Today I finally fixed the problem and all is cool now...Everything works like a charm, with no errors, all is perfect. Have a great life, be healthy, and I wish you good luck in life man. Thx for your answer.

**Comment by Daksh777** [comment]
Thank you so much @thecappadonna!
Could you please tell how you fixed the problem? It might be helpful to potential people reading it.

And you too have a great life and health as well! :D

**Comment by thecappadonna** [comment]
Well, My mistake was that I put the goToSong in a folder in extensions...and when I do spicetify Apply was giving me an error...I move the files out of the folder and no more errors...Even when I use Go to Song with 500ms delay was working like charm every day...But today I used that feature and I again receive an error to fix my delay and etc...I just can't understand where the problem is....That day I used it 1000 times and worked every single time....Today I launch my PC...Used the goTOSong and its opened my playlist but not going to the song and receive an error to check my delay up and down until make it works...Well, I spend hours with that and NEVER worked.....Any idea what delay I have to add? Or maybe the problem comes from a different place no idea...Btw...I've noticed that If I use goToSong for online songs it works well...But when I use it for my Local Libary...I receive that error...But like I said was working for my Local Music...No idea why it stopped :( if someone knows, pls give me a hint on how to fix it if possible.

**Comment by thecappadonna** [comment]
> Well, My mistake was that I put the goToSong in a folder in extensions...and when I do spicetify Apply was giving me an error...I move the files out of the folder and no more errors...Even when I use Go to Song with 500ms delay was working like charm every time...But today I used that feature and I again receive an error to fix my delay and etc...I just can't understand where the problem is....That day I used it 1000 times and worked every single time....Today I launch my PC...Used the goTOSong and its opened my playlist but not going to the song and receive an error to check my delay up and down until make it works...Well, I spend hours with that and NEVER worked.....Any idea what delay I have to add? Or maybe the problem comes from a different place no idea...Btw...I've noticed that If I use goToSong for online songs it works well...But when I use it for my Local Libary...I receive that error...But like I said was working for my Local Music...No idea why it stopped :( if someone knows, pls give me a hint on how to fix it if possible...

Just found some Delay recommendations and its works if the song is one of the first 20,30 song max...Just if the song is further down in the playlist...Again receive the error to fix my Delay....This addon just making me crazy.,..Please guys, give me some hint...Some support...I beg u "(

**Comment by thecappadonna** [comment]
This is killing me...I can't believe that some short .js file will make my problems like these...Why I didn't learn Java ffs :( Please, guys, I will really appreciate your help...Can't even express with words how grateful will be if someone tries to help me....begging u from my heart... fr...This shit is messing with my nervous system...My sleep and many others....I suffer from some strange Bipolar shit... together with depression. And when I start doing something...I can't find peace until I finish it successfully. I know that may sound stupid to some of u ...But believe me, it's the real deal and I don't recommend this shit to anybody.... Just pls, if u can help somehow....I won't forget that and u will make my daily routine much easier...

**Comment by Daksh777** [comment]
Again, @thecappadonna, please DM me either on Discord (Lars24#9047) or Telegram (https://t.me/Daksh777) and I can try to help you out. The issue is not related to my repo so I can't help here.

I strongly recommend you to open this issue in https://github.com/huhridge/huh-spicetify-extensions as well.
