### ISSUE TITLE
Broken Playlists and Bottom bar

### ISSUE THREAD

**Issue by TheKaushikGoswami** [Daksh777/SpotifyNoPremium#83]
I installed the Spicetify by following the instructions in Readme.md and It got installed.
But, I get some weird issues like distorted playlist images and all...

Here is a screenshot of that: 

![image](https://user-images.githubusercontent.com/70503983/177279605-f7ae4722-8238-477e-b64f-6fdcd1baae7d.png)

**Comment by TheKaushikGoswami** [comment]
Spotify for Windows - 1.1.88.612.gcc529952

Spicetify version = 1.1.88.612.gcc529952

**Comment by Daksh777** [comment]
Please give your Spicetify version by entering `spicetify -v` in CMD or PowerShell

**Comment by Daksh777** [comment]
I'm on the same version as you are. Could you try reinstalling Spicetify and running `update.bat` to check if it resolves the issue?

**Comment by TheKaushikGoswami** [comment]
> I'm on the same version as you are. Could you try reinstalling Spicetify and running `update.bat` to check if it resolves the issue?

How to reinstall spicetify? Is there any command for it?

**Comment by Daksh777** [comment]
Woops, I meant Spotify. You just need to uninstall Spotify and run `update.bat`

**Comment by TheKaushikGoswami** [comment]
> Woops, I meant Spotify. You just need to uninstall Spotify and run `update.bat`

U meant Reinstall Spotify? right?

**Comment by TheKaushikGoswami** [comment]
Thanks! Reinstalling Spotify and running `update.bat` fixed the issue.
