### ISSUE TITLE
when i try to run the update.bat

### ISSUE THREAD

**Issue by ale26dp** [Daksh777/SpotifyNoPremium#85]
spicetify : Termine 'spicetify' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script.
Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In C:\Users\aless\Downloads\ps.ps1:52 car:1
+ spicetify upgrade
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (spicetify:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Daksh777** [comment]
Please run `install.bat` since this is a first time install, to install Spicetify and only then use `update.bat`.
