### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Checho2463** [Daksh777/SpotifyNoPremium#95]
I have this error message, i already installed net framework 5.1 and im using win7 pro
![Sin título](https://user-images.githubusercontent.com/116528032/197425724-8dc15c88-4b93-4d3d-9651-cb97473c3ae2.png)

**Comment by Daksh777** [comment]
I understood your problem, can you try running this script and check if it works?

New script: https://drive.google.com/file/d/1sJqh4CvxX1eppEO2vD3epPvFBNROK0Fj/view?usp=sharing
